//! Regression test for #1426: a Gamma/log GAM must RECOVER the true smooth
//! (EDF ≈ 8, not the full basis), not merely terminate. On a known-failing
//! dataset gam ships a silent near-full-basis overfit (EDF ≈ 24, RMSE-to-truth
//! ~2× mgcv) while mgcv recovers EDF ≈ 8 / RMSE ≈ 0.09.
//!
//! Context: the stall-guard fix (Fix A) landed, but #1426 was reopened because
//! it is necessary-but-not-sufficient — the outer optimizer no longer aborts
//! early, yet still CONVERGES to the overfit (the default double-penalty
//! objective prefers the high-EDF solution; see #1266). Per the maintainer's
//! own close criterion, the regression test must assert the *recovered* EDF/RMSE
//! ("EDF≈8, RMSE≈0.094"), not merely "no longer stalls". This test does exactly
//! that and FAILS on current `main` — the gate the objective fix must turn green.
//!
//! Truth: mu(x) = exp(0.6·sin(2πx) + 0.6); y ~ Gamma(shape=2, scale=mu/2); n=1500,
//! default basis. Because shape=2 is integer, Gamma(2, scale) = sum of two
//! Exp(scale) draws (`-scale·(ln u1 + ln u2)`), so the dataset is generated by a
//! plain u64 LCG and is bit-reproducible here and in the Python probe (numpy's
//! RNG seeds from the original report are not portable to a Rust test; this LCG
//! seed reproduces the same Gamma/log overfit failure mode).
//!
//! METRIC (truth recovery): fit gam and mgcv on byte-identical rows; compare
//! fitted-mean-vs-true-mean RMSE. Assert (1) gam EDF is not blown up to the full
//! basis (recovery, not a certified overfit) and (2) gam is no worse than mgcv
//! by more than 10%.

use csv::StringRecord;
use gam::matrix::LinearOperator;
use gam::smooth::build_term_collection_design;
use gam::test_support::reference::{Column, rmse, run_r};
use gam::{
    FitConfig, FitResult, encode_recordswith_inferred_schema, fit_from_formula, init_parallelism,
};
use ndarray::Array2;
use std::f64::consts::PI;

const N: usize = 1500;
const LCG_SEED: u64 = 7; // reproduces the Gamma/log overfit (EDF≈24) on this truth

fn true_mu(x: f64) -> f64 {
    (0.6 * (2.0 * PI * x).sin() + 0.6).exp()
}

#[test]
fn gam_gammalog_recovers_smooth_not_full_basis_overfit() {
    init_parallelism();

    // ---- deterministic dataset via a shared u64 LCG (bit-identical to the
    //      Python probe). Gamma(shape=2, scale) = -scale·(ln u1 + ln u2). -------
    let mut state: u64 = LCG_SEED;
    let mut nxt = || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        let u = ((state >> 11) as f64) / ((1u64 << 53) as f64);
        u.clamp(1e-12, 1.0 - 1e-12)
    };
    let mut x: Vec<f64> = Vec::with_capacity(N);
    for _ in 0..N {
        x.push(nxt());
    }
    let mut y: Vec<f64> = Vec::with_capacity(N);
    for &xi in &x {
        let scale = true_mu(xi) / 2.0;
        let u1 = nxt();
        let u2 = nxt();
        y.push(-scale * (u1.ln() + u2.ln()));
    }

    // ---- fit gam: y ~ s(x), Gamma / log link (gamma's default), REML ----------
    let headers = ["x", "y"].into_iter().map(String::from).collect();
    let rows: Vec<StringRecord> = (0..N)
        .map(|i| StringRecord::from(vec![x[i].to_string(), y[i].to_string()]))
        .collect();
    let ds = encode_recordswith_inferred_schema(headers, rows).expect("encode gammalog dataset");
    let col = ds.column_map();
    let x_idx = col["x"];

    let cfg = FitConfig {
        family: Some("gamma".to_string()),
        ..FitConfig::default()
    };
    let result = fit_from_formula("y ~ s(x)", &ds, &cfg).expect("gam gamma/log fit");
    let FitResult::Standard(fit) = result else {
        panic!("expected a standard GAM fit for Gamma s(x)");
    };
    let gam_edf = fit.fit.edf_total().expect("gam reports total edf");

    // gam fitted mean at the training points: mu = exp(design·beta) (log link).
    let mut grid = Array2::<f64>::zeros((N, ds.headers.len()));
    for i in 0..N {
        grid[[i, x_idx]] = x[i];
    }
    let design = build_term_collection_design(grid.view(), &fit.resolvedspec)
        .expect("rebuild s(x) design at training points");
    let gam_mu: Vec<f64> = design
        .design
        .apply(&fit.fit.beta)
        .iter()
        .map(|e| e.exp())
        .collect();

    // ---- fit the SAME model with mgcv on the identical rows (baseline) --------
    let r = run_r(
        &[Column::new("x", &x), Column::new("y", &y)],
        r#"
        suppressPackageStartupMessages(library(mgcv))
        m <- gam(y ~ s(x), data = df, family = Gamma(link = "log"), method = "REML")
        emit("fitted", as.numeric(fitted(m)))
        emit("edf", sum(m$edf))
        "#,
    );
    let mgcv_mu = r.vector("fitted");
    let mgcv_edf = r.scalar("edf");
    assert_eq!(mgcv_mu.len(), N, "mgcv fitted length mismatch");

    // ---- recovery error vs TRUE mean ------------------------------------------
    let truth: Vec<f64> = x.iter().map(|&xi| true_mu(xi)).collect();
    let gam_err = rmse(&gam_mu, &truth);
    let mgcv_err = rmse(mgcv_mu, &truth);

    eprintln!(
        "gammalog recovery (LCG seed {LCG_SEED}): n={N} \
         gam_edf={gam_edf:.2} mgcv_edf={mgcv_edf:.2} \
         gam_rmse_vs_truth={gam_err:.5} mgcv_rmse_vs_truth={mgcv_err:.5} \
         ratio={:.2}",
        gam_err / mgcv_err.max(1e-12)
    );

    // (1) RECOVERY, not a certified overfit: a correct Gamma/log REML lands near
    //     EDF≈8 here (mgcv does); the bug leaves EDF at the full basis (~24).
    assert!(
        gam_edf < 12.0,
        "Gamma/log over-fits: EDF={gam_edf:.2} (mgcv {mgcv_edf:.2}); the optimizer \
         converges to a near-full-basis overfit instead of recovering EDF≈8 — Fix A \
         (stall guard) is insufficient; the objective/double-penalty must be fixed (#1426)"
    );

    // (2) MATCH-OR-BEAT: gam recovers the truth no worse than mgcv by >10%.
    assert!(
        gam_err <= 1.10 * mgcv_err,
        "Gamma/log fails to recover the true mean: gam_rmse={gam_err:.5} > 1.10 * \
         mgcv_rmse={mgcv_err:.5} (≈{:.0}× worse) — silent over-fit (#1426)",
        gam_err / mgcv_err.max(1e-12)
    );
}
