//! End-to-end quality: gam's penalized categorical-response model must predict
//! the same per-class probabilities as the mature Python reference for ordinal
//! regression — `statsmodels.miscmodels.ordinal_model.OrderedModel` (cumulative
//! logit) — on identical data and an identical feature design.
//!
//! ## What is being benchmarked
//!
//! gam's only categorical-response solver is the penalized multinomial-logit
//! driver `gam::families::multinomial::fit_penalized_multinomial` (the formula
//! `fit(family="multinomial")` path deliberately errors and points here). It is
//! a *nominal* softmax with `K-1` active linear predictors. The statsmodels
//! reference is the *ordinal* cumulative-logit (proportional-odds) model with
//! `K-1` shared cutpoints. These are different parameterizations of the same
//! response geometry: the proportional-odds model is nested inside the
//! unrestricted multinomial-logit (it constrains the `K-1` slope vectors to be
//! equal up to the cutpoints). On data actually generated by a latent-threshold
//! cumulative mechanism, both, fit on the *same* feature columns by maximum
//! likelihood, must recover essentially the same fitted class distribution
//! `P(Y=j | x)` and the same cumulative distribution `P(Y<=j | x)`. That shared,
//! observable quantity — the predicted probability simplex per row — is what we
//! grid-align and compare. (Thresholds/cutpoints are intrinsic to the ordinal
//! parameterization and have no per-row analog in the nominal multinomial fit,
//! so we do not assert on raw cutpoints: gam's multinomial does not emit them.)
//!
//! ## Identical inputs to both engines
//!
//! We build gam's design once — intercept + linear `x1` + cyclic cubic spline
//! basis of `x2` (`s(x2, bs="cc")`) — via the real formula → design path, then:
//!   * feed that dense design (and the smooth's block penalty) to
//!     `fit_penalized_multinomial`, and
//!   * hand the *same* design columns (dropping the intercept, which the ordinal
//!     model absorbs into its cutpoints) to `OrderedModel(distr="logit")`.
//! Both therefore see byte-identical features and the identical one-hot/coded
//! ordinal response. We fit gam with a near-zero ridge (`lambda=1e-3`) so it is
//! effectively the multinomial MLE on those basis columns — isolating the only
//! intended difference (nominal vs. cumulative link) from any smoothing-penalty
//! confound.

use gam::families::multinomial::{MultinomialFitInputs, fit_penalized_multinomial};
use gam::{
    FitConfig, FitResult, encode_recordswith_inferred_schema, fit_from_formula, init_parallelism,
};
use ndarray::{Array1, Array2, s};
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand_distr::{Distribution, Normal, Uniform};

const N: usize = 200;
const J: usize = 5; // number of ordinal levels {0,1,2,3,4}
// Latent-variable thresholds that carve the standard-logistic-ish latent into J
// ordinal bins. Y = #{c : latent > cut_c}, so there are J-1 = 4 interior cuts.
const CUTS: [f64; 4] = [-1.0, 0.0, 1.0, 2.0];

#[test]
fn gam_categorical_matches_statsmodels_ordinal() {
    init_parallelism();

    // ---- synthetic ordinal data from a latent-threshold cumulative model ----
    // latent = 0.6*x1 + smooth(x2) + N(0,1); smooth is periodic on [0,1) to suit
    // the cyclic basis. Discretize via the fixed CUTS into J levels.
    let mut rng = StdRng::seed_from_u64(20240529);
    let ux = Uniform::new(0.0, 1.0).expect("uniform x");
    let noise = Normal::new(0.0, 1.0).expect("normal noise");
    let mut x1 = vec![0.0f64; N];
    let mut x2 = vec![0.0f64; N];
    let mut y = vec![0.0f64; N];
    for i in 0..N {
        let a = ux.sample(&mut rng);
        let b = ux.sample(&mut rng);
        // periodic smooth in x2: amplitude-1 sinusoid, continuous across the seam
        let smooth = (2.0 * std::f64::consts::PI * b).sin();
        let latent = 0.6 * a + smooth + noise.sample(&mut rng);
        let level = CUTS.iter().filter(|&&c| latent > c).count();
        x1[i] = a;
        x2[i] = b;
        y[i] = level as f64;
    }

    // ---- build gam's design from the formula (intercept + x1 + cc(x2)) -------
    // We need a frozen TermCollectionSpec + materialized design at these rows.
    // The categorical driver takes a raw design + penalty, so we obtain the
    // design by fitting a throwaway Gaussian on the latent-coded response with
    // the SAME formula; that yields gam's real cyclic-spline basis columns.
    let headers = vec!["y".to_string(), "x1".to_string(), "x2".to_string()];
    let rows = (0..N)
        .map(|i| {
            csv::StringRecord::from(vec![
                y[i].to_string(),
                x1[i].to_string(),
                x2[i].to_string(),
            ])
        })
        .collect::<Vec<_>>();
    let ds = encode_recordswith_inferred_schema(headers, rows).expect("encode ordinal dataset");

    let cfg = FitConfig {
        family: Some("gaussian".to_string()),
        ..FitConfig::default()
    };
    let result = fit_from_formula("y ~ x1 + s(x2, bs=\"cc\")", &ds, &cfg)
        .expect("gam builds the x1 + cc(x2) design");
    let FitResult::Standard(fit) = result else {
        panic!("expected a standard GAM fit to expose the design");
    };

    // Dense design X (N x P): column 0 is the intercept, then x1, then the
    // cyclic-spline basis of x2.
    let design = fit
        .design
        .design
        .try_to_dense_by_chunks("ordinal multinomial design")
        .expect("materialize gam design");
    let n = design.nrows();
    let p = design.ncols();
    assert_eq!(n, N, "design row count");
    assert!(p >= 3, "expect intercept + x1 + >=1 smooth column, got P={p}");

    // Shared P x P smooth penalty: assemble the smooth's blockwise local penalty
    // into the global coordinate frame (intercept + x1 blocks are unpenalized).
    let mut penalty = Array2::<f64>::zeros((p, p));
    for blk in &fit.design.penalties {
        let r = blk.col_range.clone();
        penalty.slice_mut(s![r.clone(), r.clone()]).assign(&blk.local);
    }

    // One-hot response Y (N x J).
    let mut y_one_hot = Array2::<f64>::zeros((n, J));
    for i in 0..n {
        let lvl = y[i] as usize;
        assert!(lvl < J, "ordinal level out of range");
        y_one_hot[[i, lvl]] = 1.0;
    }

    // ---- fit gam's penalized multinomial-logit at near-zero ridge -----------
    // lambda small => effectively the multinomial MLE on these exact columns,
    // so the only difference from the reference is nominal vs. cumulative link.
    let lambdas = Array1::from_elem(J - 1, 1e-3);
    let out = fit_penalized_multinomial(MultinomialFitInputs {
        design: design.view(),
        y_one_hot: y_one_hot.view(),
        penalty: penalty.view(),
        lambdas: lambdas.view(),
        row_weights: None,
        fisher_w_override: None,
        max_iter: 100,
        tol: 1e-9,
    })
    .expect("gam multinomial fit converges");
    assert!(out.converged, "gam multinomial did not converge");
    let gam_probs = out.fitted_probabilities; // (N, J)
    assert_eq!(gam_probs.dim(), (n, J));

    // ---- fit the SAME data with statsmodels OrderedModel (cumulative logit) -
    // We pass gam's design columns 1..P (drop the intercept; OrderedModel folds
    // the intercept into its cutpoints) as the exogenous matrix, so both engines
    // see identical features. Returns per-row class probabilities, row-major.
    use gam::test_support::reference::{Column, run_python};
    let mut cols: Vec<Column<'_>> = Vec::with_capacity(p);
    cols.push(Column::new("y", &y));
    // Materialize each design column (skip intercept at index 0) as a named col.
    let design_cols: Vec<Vec<f64>> = (1..p)
        .map(|j| design.column(j).to_vec())
        .collect();
    let col_names: Vec<String> = (1..p).map(|j| format!("d{j}")).collect();
    for (name, data) in col_names.iter().zip(design_cols.iter()) {
        cols.push(Column::new(name.as_str(), data));
    }

    let py_body = format!(
        r#"
import numpy as np
from statsmodels.miscmodels.ordinal_model import OrderedModel

names = {names:?}
X = np.column_stack([np.asarray(df[c], dtype=float) for c in names])
yv = np.asarray(df["y"], dtype=float).astype(int)

# Cumulative logit (proportional-odds) ordinal model on the identical features.
m = OrderedModel(yv, X, distr="logit")
res = m.fit(method="bfgs", maxiter=2000, disp=False)
probs = res.model.predict(res.params, exog=X)   # (N, J) per-class probabilities
emit("probs", probs.reshape(-1))                  # row-major flatten
emit("nclass", [probs.shape[1]])
"#,
        names = col_names
    );
    let r = run_python(&cols, &py_body);
    let nclass = r.scalar("nclass") as usize;
    assert_eq!(nclass, J, "statsmodels recovered {nclass} classes, expected {J}");
    let ref_flat = r.vector("probs");
    assert_eq!(ref_flat.len(), n * J, "reference prob matrix size mismatch");

    // ---- compare predicted class probabilities & cumulative probabilities ---
    // Flatten gam's (N,J) row-major to align with statsmodels' row-major flatten.
    let mut gam_flat = Vec::<f64>::with_capacity(n * J);
    for i in 0..n {
        for j in 0..J {
            gam_flat.push(gam_probs[[i, j]]);
        }
    }

    // Per-row cumulative probabilities P(Y<=j), j = 0..J-2 (the last is 1).
    let mut gam_cum = vec![vec![0.0f64; J - 1]; n];
    let mut ref_cum = vec![vec![0.0f64; J - 1]; n];
    for i in 0..n {
        let mut g = 0.0;
        let mut s = 0.0;
        for j in 0..(J - 1) {
            g += gam_probs[[i, j]];
            s += ref_flat[i * J + j];
            gam_cum[i][j] = g;
            ref_cum[i][j] = s;
        }
    }
    // Max-abs cumulative diff per level across rows.
    let mut max_cum_diff_per_level = vec![0.0f64; J - 1];
    for level in 0..(J - 1) {
        let mut m = 0.0f64;
        for i in 0..n {
            m = m.max((gam_cum[i][level] - ref_cum[i][level]).abs());
        }
        max_cum_diff_per_level[level] = m;
    }

    // L2-relative on the full class-probability simplex.
    let class_rel_l2 = gam::test_support::reference::relative_l2(&gam_flat, ref_flat);
    let class_max_abs = gam::test_support::reference::max_abs_diff(&gam_flat, ref_flat);
    let worst_cum = max_cum_diff_per_level
        .iter()
        .cloned()
        .fold(0.0f64, f64::max);

    eprintln!(
        "ordinal vs statsmodels OrderedModel(logit): n={n} J={J} P={p} \
         class_rel_l2={class_rel_l2:.4} class_max_abs={class_max_abs:.4} \
         cum_max_abs_per_level={max_cum_diff_per_level:?} worst_cum={worst_cum:.4} \
         gam_iters={iters} gam_dev={dev:.3}",
        iters = out.iterations,
        dev = out.deviance
    );

    // ---- principled agreement bounds ----------------------------------------
    // The proportional-odds model is a constrained submodel of the unrestricted
    // multinomial-logit; on data generated by a genuine latent-threshold
    // cumulative mechanism with smooth covariate effects, both maximum-likelihood
    // fits on the SAME basis recover the same conditional simplex up to the
    // sampling-level slack of n=200 rows. The bounds below are the spec's
    // calibration tolerances:
    //   * cumulative P(Y<=j): max-abs diff per level < 0.02 — tight enough that
    //     any systematic divergence in the cumulative-link formulation fails it.
    //   * class probabilities: relative L2 < 0.025 over the whole (N,J) simplex.
    // These assert agreement of the observable quantity (the predicted
    // distribution), not of internal parameterizations. A genuine divergence
    // failing here is a real, useful signal — do not loosen.
    for (level, &d) in max_cum_diff_per_level.iter().enumerate() {
        assert!(
            d < 0.02,
            "cumulative P(Y<={level}) diverges from statsmodels: max-abs={d:.4} (bound 0.02)"
        );
    }
    assert!(
        class_rel_l2 < 0.025,
        "class probabilities diverge from statsmodels OrderedModel: rel_l2={class_rel_l2:.4} (bound 0.025)"
    );
}
