//! Full-width affine baseline: extract TRAIN_EXPORT EVAL_EXPORT OUT TRACE_BYTES
//! or fit EVAL_EXPORT EXTRACT OUT MAX_BANK [save_index=N]. Fixed 8 train/2 eval
//! complete 512-token sequences, all four layers. evaluate EVAL_EXPORT FIT_DIR
//! SPEC OUT FITS_SHA SPEC_SHA TRACE_BYTES performs separately decoded Local/Run.
use gam_mpd::{affine_mlp::{AffineFit,residual_spectrum},artifact::Artifact,acceptance::{CostCache,structural_cost},coder_capture::sha256,device_program::DeviceProgram,import::import_language_model,operator_program::SlotValues,run_check::{split_sites,layer_nodes}};
use ndarray::Array2;
use serde_json::{Value,json};
use std::{path::Path,io::Write,time::Instant};
const CONTEXT:usize=512;
const RANKS:&[usize]=&[0,8,32,64,96,128,256,512,768];
fn save(path:&Path,value:&Value)->Result<(),String>{std::fs::write(path,serde_json::to_vec_pretty(value).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
fn fresh(path:&Path)->Result<(),String>{std::fs::create_dir(path).map_err(|e|format!("fresh output required: {e}"))}
fn read(path:&Path,rows:usize,width:usize,hash:&str)->Result<Array2<f64>,String>{
 let bytes=std::fs::read(path).map_err(|e|e.to_string())?;let size=rows.checked_mul(width).and_then(|n|n.checked_mul(8)).ok_or("matrix size overflow")?;
 if bytes.len()!=size || sha256(path)?!=hash{return Err("captured response size/hash mismatch".into());}
 let values=bytes.chunks_exact(8).map(|b|f64::from_le_bytes(b.try_into().expect("exact eight-byte chunks"))).collect();Array2::from_shape_vec((rows,width),values).map_err(|e|e.to_string())
}
fn main()->Result<(),String>{run()}
fn run()->Result<(),String>{let a:Vec<_>=std::env::args().skip(1).collect();match a.first().map(String::as_str){Some("extract") if a.len()==5=>extract(&a[1..]),Some("fit") if (5..=6).contains(&a.len())=>fit(&a[1..]),Some("evaluate") if a.len()==8=>evaluate(&a[1..]),_=>Err("extract TRAIN_EXPORT EVAL_EXPORT OUT TRACE_BYTES | fit EVAL_EXPORT EXTRACT OUT MAX_BANK [save_index=N]".into())}}
fn extract(a:&[String])->Result<(),String>{
 let clock=Instant::now();let budget=a[3].parse::<usize>().map_err(|e|e.to_string())?;
 let train=import_language_model(Path::new(&a[0]),8,CONTEXT)?;let eval=import_language_model(Path::new(&a[1]),2,CONTEXT)?;
 if train.record["config"]["n_layers"].as_u64()!=Some(4) || train.record["source"]["checkpoint_sha256"]!=eval.record["source"]["checkpoint_sha256"] || train.record["config"]!=eval.record["config"]{return Err("same checkpoint/config and exactly four native layers required".into());}
 let (Some(SlotValues::Tokens(t)),Some(SlotValues::Tokens(e)))=(train.contract.family.slots.first(),eval.contract.family.slots.first()) else{return Err("native token inputs required".into());};
 let sequences:std::collections::BTreeSet<_>=t.chunks_exact(CONTEXT).collect();if e.chunks_exact(CONTEXT).any(|s|sequences.contains(s)){return Err("train/evaluation token sequences overlap".into());}
 let native=split_sites(&train.program)?;let other=split_sites(&eval.program)?;
 if native.nodes!=other.nodes || native.operators.len()!=other.operators.len() || native.operators.iter().zip(&other.operators).any(|(x,y)|x.name!=y.name || x.matrix_cow()!=y.matrix_cow()){return Err("actual native graph/weights differ between exports".into());}
 let layers=layer_nodes(&native,4)?;let interfaces=native.interfaces().map_err(|e|e.to_string())?;
 if layers.iter().any(|l|interfaces[l.normed].width()!=768 || interfaces[l.mlp].width()!=768){return Err("declared four-layer width768 baseline required".into());}
 // Execute original numeric literals, not f32-projected approximation; avoid the
 // final vocabulary readout by ending the graph at the final residual stream.
 let mut prefix=native.clone();prefix.output=layers.last().ok_or("layers absent")?.residual;prefix.nodes.truncate(prefix.output+1);
 let device=gam_gpu::tensor::Device::accelerator(gam_gpu::GpuPolicy::Required).map_err(|e|e.to_string())?.ok_or("CUDA required")?;if !device.float64(){return Err("float64 CUDA required".into());}
 let resident=DeviceProgram::compile_values(&device,&prefix)?;let one=resident.bytes_per_row().checked_mul(CONTEXT).ok_or("trace size overflow")?;let batch_sequences=(budget/one).min(8);if batch_sequences==0{return Err(format!("complete sequence needs {one} trace bytes"));}let batch_rows=batch_sequences*CONTEXT;
 let out=Path::new(&a[2]);fresh(out)?;let mut panels=Vec::new();
 for (name,imported) in [("train",&train),("eval",&eval)]{
  let start=Instant::now();let family=&imported.contract.family;
  for at in (0..family.rows).step_by(batch_rows){let end=(at+batch_rows).min(family.rows);if end%CONTEXT!=0{return Err("incomplete causal batch".into());}let batch=family.select(&(at..end).collect::<Vec<_>>());let trace=resident.forward(&batch)?;
   for (layer,nodes) in layers.iter().enumerate(){for (role,node) in [("input",nodes.normed),("write",nodes.mlp)]{let matrix=device.download(trace.value(node)?).map_err(|e|e.to_string())?;if matrix.iter().any(|v|!v.is_finite()){return Err("nonfinite native extraction".into());}let bytes:Vec<_>=matrix.iter().flat_map(|v|v.to_le_bytes()).collect();std::fs::OpenOptions::new().create_new(at==0).append(true).open(out.join(format!("{name}.{layer}.{role}.f64"))).map_err(|e|e.to_string())?.write_all(&bytes).map_err(|e|e.to_string())?;}}
   eprintln!("extracted {name} {end}/{} native rows",family.rows);
  }
  let mut records=Vec::new();for (layer,nodes) in layers.iter().enumerate(){for(role,node)in[("input",nodes.normed),("write",nodes.mlp)]{let file=format!("{name}.{layer}.{role}.f64");records.push(json!({"layer":layer,"role":role,"native_node":node,"width":interfaces[node].width(),"file":file,"sha256":sha256(&out.join(&file))?}));}}
  panels.push(json!({"name":name,"rows":family.rows,"record":imported.record,"values":records,"extraction_seconds":start.elapsed().as_secs_f64()}));
 }
 save(&out.join("EXTRACT.json"),&json!({"scope":"original native full causal responses; no final logits, no fit or acceptance","context":CONTEXT,"train_sequences":8,"eval_sequences":2,"prefix_output":prefix.output,"trace_budget":budget,"requested_trace_bytes":batch_rows*resident.bytes_per_row(),"operator_numeric_bytes":resident.operator_numeric_bytes()?,"panels":panels,"elapsed_seconds":clock.elapsed().as_secs_f64()}))
}
fn fit(a:&[String])->Result<(),String>{
 let max=a[3].parse::<usize>().map_err(|e|e.to_string())?;if max<6{return Err("complete native+four single-layer+joint bank needs max_bank>=6".into());}
 let selected=if let Some(arg)=a.get(4){Some(arg.strip_prefix("save_index=").ok_or("expected save_index=N")?.parse::<usize>().map_err(|e|e.to_string())?)}else{None};if selected.is_some_and(|i|i>=6){return Err("save_index outside complete six-candidate bank".into());}
 let clock=Instant::now();let data=Path::new(&a[1]);let manifest_bytes=std::fs::read(data.join("EXTRACT.json")).map_err(|e|e.to_string())?;let manifest:Value=serde_json::from_slice(&manifest_bytes).map_err(|e|e.to_string())?;
 if manifest["context"].as_u64()!=Some(512)||manifest["train_sequences"].as_u64()!=Some(8)||manifest["eval_sequences"].as_u64()!=Some(2){return Err("frozen complete sequence scope mismatch".into());}
 let imported=import_language_model(Path::new(&a[0]),2,CONTEXT)?;let native=split_sites(&imported.program)?;let layers=layer_nodes(&native,4)?;if imported.record!=manifest["panels"][1]["record"]{return Err("evaluation source manifest mismatch".into());}
 let out=Path::new(&a[2]);fresh(out)?;let mut journal=std::fs::File::create(out.join("FITS.jsonl")).map_err(|e|e.to_string())?;let mut fits=Vec::new();
 for(layer,nodes)in layers.iter().enumerate(){let mut arrays=Vec::new();for(panel,rows)in [(0,4096),(1,1024)]{for(role,node)in[("input",nodes.normed),("write",nodes.mlp)]{let records=manifest["panels"][panel]["values"].as_array().ok_or("extraction records")?;let record=records.iter().find(|r|r["layer"].as_u64()==Some(layer as u64)&&r["role"].as_str()==Some(role)).ok_or("missing native layer response")?;if record["native_node"].as_u64()!=Some(node as u64)||record["width"].as_u64()!=Some(768){return Err("captured interface mismatch".into());}arrays.push(read(&data.join(record["file"].as_str().ok_or("file")?),rows,768,record["sha256"].as_str().ok_or("hash")?)?);}}
  let start=Instant::now();let proposal=AffineFit::fit(&arrays[0],&arrays[1])?;let train_curve=residual_spectrum(&proposal,&arrays[0],&arrays[1],RANKS)?;let eval_curve=residual_spectrum(&proposal,&arrays[2],&arrays[3],RANKS)?;let heldout_base=proposal.predict(&arrays[2])?;let heldout_file=format!("eval.{layer}.base.f64");let heldout_bytes:Vec<_>=heldout_base.iter().flat_map(|v|v.to_le_bytes()).collect();std::fs::write(out.join(&heldout_file),&heldout_bytes).map_err(|e|e.to_string())?;
  let record=json!({"layer":layer,"native_input":nodes.normed,"native_write":nodes.mlp,"numerical_convention":"augmented-design minimum coefficient norm at maxdim*eps*sigma_max; not discovery","training_rows":proposal.training_rows,"numerical_rank":proposal.numerical_rank,"numerical_resolution":proposal.numerical_resolution,"augmented_singular_values":proposal.augmented_singular_values.to_vec(),"weights":proposal.weights,"offset":proposal.offset,"train":train_curve,"eval":eval_curve,"heldout_base":{"file":heldout_file,"rows":1024,"width":768,"sha256":sha256(&out.join(&heldout_file))?},"fit_seconds":start.elapsed().as_secs_f64()});writeln!(journal,"{record}").map_err(|e|e.to_string())?;journal.flush().map_err(|e|e.to_string())?;fits.push(proposal);eprintln!("fitted complete width768 layer {layer}");
 }
 let base=Artifact::native(&native)?.f32_literals()?;let mut costs=Vec::new();let mut cache=CostCache::default();for index in 0..6{let mut candidate=base.clone();let chosen:Vec<_>=if index==0{vec![]}else if index==5{(0..4).collect()}else{vec![index-1]};for layer in &chosen{candidate=fits[*layer].candidate(&candidate,&native,&layers[*layer],&format!("affine{layer}"))?;}candidate.validate_coverage(&native)?;let cost=structural_cost(&candidate,&mut cache)?;costs.push(json!({"index":index,"layers":chosen,"cost":cost}));if selected==Some(index){let bytes=candidate.to_bytes()?;let decoded=Artifact::from_bytes(&bytes,&native.declarations)?;decoded.validate_coverage(&native)?;if decoded.to_bytes()?!=bytes||structural_cost(&decoded,&mut CostCache::default())?!=cost{return Err("ordinary saved-byte parity failed".into());}std::fs::write(out.join("selected.artifact"),&bytes).map_err(|e|e.to_string())?;save(&out.join("SELECTED.json"),&json!({"index":index,"sha256":sha256(&out.join("selected.artifact"))?,"bytes":bytes.len(),"cost":cost}))?;}cache.clear_measurements();}
 save(&out.join("REPORT.json"),&json!({"scope":"six finite full-dimensional affine proposals; no Local or Run evidence; fixed f32 base plus ideal rank/offset diagnostic only","extraction_sha256":sha256(&data.join("EXTRACT.json"))?,"record":imported.record,"context":512,"train_sequences":8,"eval_sequences":2,"ranks":RANKS,"bank":costs,"max_bank":max,"selected":selected,"elapsed_seconds":clock.elapsed().as_secs_f64()}))
}

/// Frozen six-artifact decoded full-context Local first, then the fixed eighty
/// native-reference episodes only when widest declared Local is not refuted.
fn evaluate(a:&[String])->Result<(),String>{
 use gam_mpd::{acceptance::{Constraint,Local,assess_once_local_first_with_native_codec},counterfactual::{Decoder,Spec,passages},operator_program::NativeOperatorCodec,run_check::LanguageRun};
 let export=Path::new(&a[0]);let fit_dir=Path::new(&a[1]);let spec_path=Path::new(&a[2]);let out=Path::new(&a[3]);
 if sha256(&fit_dir.join("FITS.jsonl"))?!=a[4] || sha256(spec_path)?!=a[5]{return Err("frozen fit/spec hashes changed".into());}
 let trace_bytes=a[6].parse::<usize>().map_err(|e|e.to_string())?;
 let imported=import_language_model(export,2,CONTEXT)?;let native=split_sites(&imported.program)?;let layers=layer_nodes(&native,4)?;
 let report:Value=serde_json::from_slice(&std::fs::read(fit_dir.join("REPORT.json")).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;
 if report["record"]!=imported.record || report["bank"].as_array().map(Vec::len)!=Some(6){return Err("complete frozen fit source/bank mismatch".into());}
 let mut fits=Vec::new();for(expected,line)in std::fs::read_to_string(fit_dir.join("FITS.jsonl")).map_err(|e|e.to_string())?.lines().enumerate(){if expected>=4{return Err("extra fitted layer record".into());}let r:Value=serde_json::from_str(line).map_err(|e|e.to_string())?;if r["layer"].as_u64()!=Some(expected as u64){return Err("all four ordered native layers required".into());}fits.push(AffineFit{weights:serde_json::from_value(r["weights"].clone()).map_err(|e|e.to_string())?,offset:serde_json::from_value(r["offset"].clone()).map_err(|e|e.to_string())?,training_rows:4096,augmented_singular_values:ndarray::Array1::from_vec(serde_json::from_value(r["augmented_singular_values"].clone()).map_err(|e|e.to_string())?),numerical_resolution:r["numerical_resolution"].as_f64().ok_or("resolution")?,numerical_rank:r["numerical_rank"].as_u64().ok_or("rank")? as usize});}if fits.len()!=4{return Err("four fitted native layers required".into());}
 let decoder=Decoder::from_export(export)?;let spec=Spec::load(spec_path,&decoder)?;if spec.rows!=512||spec.episodes.len()!=80{return Err("frozen eighty-episode full512 protocol required".into());}
 let rows=passages(export,512)?;let device=gam_gpu::tensor::Device::accelerator(gam_gpu::GpuPolicy::Required).map_err(|e|e.to_string())?.ok_or("CUDA required")?;
 let local=Local::new(&native,imported.contract.family.clone(),None,16).with_cuda(device.clone(),trace_bytes)?;
 let run=LanguageRun::new(&decoder,&native,&spec,&rows,1)?.with_cuda(device,trace_bytes)?;
 let codec=NativeOperatorCodec::new(&native,2*1024*1024*1024).map_err(|e|e.to_string())?;
 let grid:Vec<_>=[0.01,0.05,0.1,0.2,0.5,1.0].into_iter().flat_map(|delta|[0.001,0.01,0.03,0.1,0.3,1.0].into_iter().map(move|epsilon|Constraint{local:delta,run:epsilon})).collect();
 let base=Artifact::native(&native)?.f32_literals()?;fresh(out)?;save(&out.join("PROTOCOL.json"),&json!({"scope":"complete six fitted affine programs, finite scope only; original pureMLP contribution Local boundary","fits_sha256":a[4],"spec_sha256":a[5],"grid":grid,"episodes":80,"local_rows":1024,"context":512,"trace_bytes":trace_bytes,"native_sharing":false,"codec_bytes":2*1024*1024*1024_u64,"binary_sha256":sha256(&std::env::current_exe().map_err(|e|e.to_string())?)?,"numerical_model":"conditional CPU exp2ULP/log1ULP accuracy, no unconditional certificate"}))?;
 let mut journal=std::fs::File::create(out.join("ASSESSMENTS.jsonl")).map_err(|e|e.to_string())?;let mut cache=CostCache::default();let mut records=Vec::new();
 for index in 0..6{let clock=Instant::now();let mut candidate=base.clone();let chosen:Vec<_>=if index==0{vec![]}else if index==5{(0..4).collect()}else{vec![index-1]};for layer in &chosen{candidate=fits[*layer].candidate(&candidate,&native,&layers[*layer],&format!("affine{layer}"))?;}let cost=structural_cost(&candidate,&mut cache)?;
  let record=match assess_once_local_first_with_native_codec(&local,&run,&candidate,&grid,&mut cache,&codec){Ok(staged)=>{let verdicts=grid.iter().map(|&point|staged.verdict(point).map(|v|format!("{v:?}"))).collect::<Result<Vec<_>,_>>()?;json!({"index":index,"layers":chosen,"cost":cost,"cost_bits":cost.total(),"states":verdicts,"local":match &staged{gam_mpd::acceptance::StagedAssessment::Complete(a)=>&a.local_measure,gam_mpd::acceptance::StagedAssessment::LocalRejected{local_measure,..}=>local_measure},"run":staged.run_measure(),"seconds":clock.elapsed().as_secs_f64()})},Err(error)=>json!({"index":index,"layers":chosen,"cost":cost,"cost_bits":cost.total(),"error":error,"states":vec!["Unresolved";grid.len()],"seconds":clock.elapsed().as_secs_f64()})};writeln!(journal,"{record}").map_err(|e|e.to_string())?;journal.flush().map_err(|e|e.to_string())?;records.push(record);cache.clear_measurements();eprintln!("assessed affine bank {index}/5");
 }
 let mut points=Vec::new();let mut selected=std::collections::BTreeSet::new();
 for (g,point) in grid.iter().enumerate(){let lower=records.iter().filter(|r|r["states"][g].as_str()!=Some("Violates")).filter_map(|r|r["cost_bits"].as_u64()).min();let upper=records.iter().filter(|r|r["states"][g].as_str()==Some("Meets")).filter_map(|r|Some((r["cost_bits"].as_u64()?,r["index"].as_u64()? as usize))).min();if let Some((_,index))=upper{selected.insert(index);}points.push(json!({"constraint":point,"lower_cost":lower,"upper_cost":upper.map(|p|p.0),"selected":upper.map(|p|p.1),"gap":upper.and_then(|u|lower.map(|l|u.0-l))}));}
 let mut replays=Vec::new();for index in selected{let mut candidate=base.clone();let chosen:Vec<_>=if index==0{vec![]}else if index==5{(0..4).collect()}else{vec![index-1]};for layer in chosen{candidate=fits[layer].candidate(&candidate,&native,&layers[layer],&format!("affine{layer}"))?;}let bytes=candidate.to_bytes()?;let decoded=Artifact::from_bytes(&bytes,&native.declarations)?;decoded.validate_coverage(&native)?;if decoded.to_bytes()?!=bytes || structural_cost(&decoded,&mut CostCache::default())?.total()!=records[index]["cost_bits"].as_u64().ok_or("winner price")?{return Err("selected ordinary saved replay mismatch".into());}let file=format!("selected-{index}.artifact");std::fs::write(out.join(&file),bytes).map_err(|e|e.to_string())?;replays.push(json!({"index":index,"file":file,"sha256":sha256(&out.join(&file))?,"ordinary_decode_canonical_coverage_cost":true}));}
 save(&out.join("REPORT.json"),&json!({"scope":"all six fitted programs; errors retained unresolved; not global affine optimum","grid":grid,"records":records,"points":points,"selected_saved_replays":replays,"codec":codec.stats(),"run_timing":run.timing()}))
}
