//! Objective quality of gam's pointwise confidence intervals on a Gaussian
//! smooth: do the standard errors gam derives from its Bayesian coefficient
//! covariance (`Vb`/`Vp`) yield confidence intervals that actually COVER the
//! truth at their nominal rate?
//!
//! METRIC ASSERTED (CALIBRATION / coverage): we simulate many replicates from a
//! KNOWN smooth `f(x)`, fit `y ~ s(x)` with gam on each, form the nominal-95%
//! pointwise CI for the fitted linear predictor `η̂(x) = f̂(x)` as
//! `η̂(x) ± z·sqrt(xᵀ Vb x)`, and measure the empirical fraction of replicates
//! whose interval contains the true `f(x)`, pooled across the evaluation grid.
//! A correct SE makes that empirical coverage land near 0.95. We assert the
//! pooled coverage is within an absolute tolerance of nominal — an OBJECTIVE
//! statement about gam alone (an SE that is too small under-covers; one that is
//! too large over-covers; either is a real calibration bug). This is Wood's
//! "across-the-function" Bayesian coverage property (Nychka 1988; Wood 2006,
//! §4.8), the actual quality claim behind a confidence band.
//!
//! BASELINE TO MATCH-OR-BEAT: mgcv fits the identical replicates and forms its
//! own `predict(se.fit=TRUE)` intervals; we require gam's coverage error
//! `|cov − 0.95|` to be no worse than mgcv's by more than a small slack. mgcv is
//! NOT ground truth here — it is the established baseline on the same objective
//! calibration metric. We additionally print the rel-L2 of the per-rep SE
//! vectors for context, but it is NOT a pass criterion.
//!
//! The design points and the per-replicate noise are generated by a fixed,
//! deterministic RNG in Rust and handed to BOTH engines as identical columns, so
//! gam and mgcv fit byte-identical responses; any coverage gap is a property of
//! the covariance/SE computation, not of the data.

use csv::StringRecord;
use gam::matrix::LinearOperator;
use gam::smooth::build_term_collection_design;
use gam::test_support::reference::{Column, relative_l2, run_r};
use gam::{
    FitConfig, FitResult, encode_recordswith_inferred_schema, fit_from_formula, init_parallelism,
};
use ndarray::{Array1, Array2};
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};

/// Deterministic SplitMix64 -> standard-normal stream (Box–Muller). Keeps the
/// simulation reproducible without an external RNG crate, and lets us emit the
/// exact same noise to R.
struct NormalStream {
    state: u64,
    spare: Option<f64>,
}

impl NormalStream {
    fn new(seed: u64) -> Self {
        Self {
            state: seed.wrapping_add(0x9E37_79B9_7F4A_7C15),
            spare: None,
        }
    }

    fn next_u64(&mut self) -> u64 {
        // SplitMix64.
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform in (0, 1).
    fn next_uniform(&mut self) -> f64 {
        // 53-bit mantissa, shifted off zero so log() in Box–Muller is finite.
        let bits = self.next_u64() >> 11;
        (bits as f64 + 0.5) * (1.0 / (1u64 << 53) as f64)
    }

    /// Standard normal via Box–Muller.
    fn next_normal(&mut self) -> f64 {
        if let Some(z) = self.spare.take() {
            return z;
        }
        let u1 = self.next_uniform();
        let u2 = self.next_uniform();
        let r = (-2.0 * u1.ln()).sqrt();
        let theta = std::f64::consts::TAU * u2;
        self.spare = Some(r * theta.sin());
        r * theta.cos()
    }
}

/// Known smooth truth on x ∈ [0, 1]. A single sine bump plus mild linear trend:
/// curvature high enough that a real smooth (edf > 1) is needed, smooth enough
/// that the default thin-plate basis can represent it with negligible bias.
fn truth(x: f64) -> f64 {
    (std::f64::consts::TAU * x).sin() + 0.5 * x
}

#[test]
fn gam_pointwise_ci_covers_truth_and_matches_mgcv_on_gaussian_smooth() {
    init_parallelism();

    // ---- simulation design (fixed) ---------------------------------------
    let n: usize = 200; // training points per replicate
    // Simulation replicates. The cost is dominated by `reps` full gam fits plus
    // `reps` mgcv REML fits; the sibling coverage tests run 30–50 reps and pass
    // in ~125 s, while this variant's original 240 reps overran the 360 s
    // reference-quality timeout. 60 reps pools 60×200 = 12 000 interval checks,
    // whose Monte-Carlo SE on a coverage proportion is ≈ sqrt(0.95·0.05/12000)
    // ≈ 0.002 — an order of magnitude below the ±0.04 calibration band asserted
    // below, so the coverage claim keeps its statistical power unchanged.
    let reps: usize = 60; // simulation replicates
    let sigma: f64 = 0.30; // noise SD on the response
    let z: f64 = 1.959_963_984_540_054; // 97.5% standard-normal quantile

    // Evenly spaced design on [0, 1], shared by every replicate and both engines.
    let x: Vec<f64> = (0..n).map(|i| i as f64 / (n as f64 - 1.0)).collect();
    let f_true: Vec<f64> = x.iter().map(|&xi| truth(xi)).collect();

    // Per-replicate responses y[k][i] = f(x_i) + sigma * eps. One deterministic
    // normal stream so the whole experiment is reproducible; the SAME y columns
    // go to gam and to mgcv.
    let mut rng = NormalStream::new(0x5161_D131_C0FF_EE01);
    let mut y_reps: Vec<Vec<f64>> = Vec::with_capacity(reps);
    for _ in 0..reps {
        let mut yk = Vec::with_capacity(n);
        for &ft in &f_true {
            yk.push(ft + sigma * rng.next_normal());
        }
        y_reps.push(yk);
    }

    // ---- gam: fit each replicate, build the 95% pointwise CI for η̂(x), and
    //      tally empirical coverage of the known truth f(x). ----------------
    let cfg = FitConfig {
        family: Some("gaussian".to_string()),
        ..FitConfig::default()
    };

    // For context only: rel-L2 between gam's and mgcv's per-rep SE vector,
    // averaged over replicates. NOT a pass criterion.
    // The 60 replicate fits are independent (only `y` changes); each produces a
    // per-rep `(hit_count, se_vector)`. Fanning them across the rayon pool and
    // collecting in replicate order is bit-identical to the serial version —
    // `gam_hit`/`gam_total` are exact integer sums and `gam_se_by_rep` keeps its
    // order — so no asserted quantity changes. The fits dominate wall-clock, so
    // this is the harness-side speedup (#1082).
    let per_rep: Vec<(usize, Vec<f64>)> = y_reps
        .par_iter()
        .map(|yk| {
            // Build an in-memory dataset (x, y) for this replicate, identical
            // numerically to what R receives.
            let headers = vec!["x".to_string(), "y".to_string()];
            let records: Vec<StringRecord> = (0..n)
                .map(|i| {
                    StringRecord::from(vec![format!("{:.17e}", x[i]), format!("{:.17e}", yk[i])])
                })
                .collect();
            let ds = encode_recordswith_inferred_schema(headers, records)
                .expect("encode simulated replicate");
            let col = ds.column_map();
            let x_idx = col["x"];

            let result = fit_from_formula("y ~ s(x)", &ds, &cfg).expect("gam fit");
            let FitResult::Standard(fit) = result else {
                panic!("expected a standard GAM fit");
            };

            let vb = fit
                .fit
                .beta_covariance()
                .expect("gam reports Bayesian coefficient covariance Vb")
                .clone();
            let beta = fit.fit.beta.clone();
            let p = beta.len();
            assert_eq!(vb.nrows(), p, "Vb dimension must match coefficient count");

            // Rebuild the frozen design at the (shared) x grid. Identity link, so
            // the design row is exactly ∂η/∂β and η̂ = X·β.
            let mut grid = Array2::<f64>::zeros((n, ds.headers.len()));
            for (i, &xi) in x.iter().enumerate() {
                grid[[i, x_idx]] = xi;
            }
            let design = build_term_collection_design(grid.view(), &fit.resolvedspec)
                .expect("rebuild design at grid points");
            assert_eq!(design.design.ncols(), p, "design cols must match coeff dim");
            assert_eq!(design.design.nrows(), n, "design rows must match grid");

            // Dense X by applying the operator to each unit basis vector.
            let mut x_dense = Array2::<f64>::zeros((n, p));
            for j in 0..p {
                let mut e_j = Array1::<f64>::zeros(p);
                e_j[j] = 1.0;
                let col_j = design.design.apply(&e_j);
                for i in 0..n {
                    x_dense[[i, j]] = col_j[i];
                }
            }

            // η̂(x) = X·β and pointwise SE = sqrt(xᵀ Vb x).
            let eta_hat = design.design.apply(&beta);
            let mut se = Vec::with_capacity(n);
            for i in 0..n {
                let xi = x_dense.row(i);
                let vbxi = vb.dot(&xi);
                se.push(xi.dot(&vbxi).max(0.0).sqrt());
            }

            let mut hit = 0usize;
            for i in 0..n {
                let lo = eta_hat[i] - z * se[i];
                let hi = eta_hat[i] + z * se[i];
                if f_true[i] >= lo && f_true[i] <= hi {
                    hit += 1;
                }
            }
            (hit, se)
        })
        .collect();

    let mut gam_hit = 0usize;
    let mut gam_total = 0usize;
    let mut gam_se_by_rep: Vec<Vec<f64>> = Vec::with_capacity(reps);
    for (hit, se) in per_rep {
        gam_hit += hit;
        gam_total += n;
        gam_se_by_rep.push(se);
    }

    let gam_coverage = gam_hit as f64 / gam_total as f64;

    // ---- mgcv: same replicates, its own 95% pointwise CI, its own coverage.
    // R receives x, the true f, and one y column per replicate; it fits
    // `y_k ~ s(x)` by REML, builds η̂ ± z·se.fit, and tallies coverage of f. ---
    let mut cols: Vec<Column<'_>> = Vec::with_capacity(reps + 2);
    cols.push(Column::new("x", &x));
    cols.push(Column::new("ftrue", &f_true));
    let yk_names: Vec<String> = (0..reps).map(|k| format!("y{k}")).collect();
    for (k, yk) in y_reps.iter().enumerate() {
        cols.push(Column::new(yk_names[k].as_str(), yk));
    }

    let r = run_r(
        &cols,
        &format!(
            r#"
            suppressPackageStartupMessages(library(mgcv))
            reps <- {reps}
            z <- {z}
            hit <- 0
            tot <- 0
            se_flat <- numeric(0)
            for (k in 0:(reps - 1)) {{
                yk <- df[[paste0("y", k)]]
                d <- data.frame(x = df$x, y = yk)
                m <- gam(y ~ s(x), data = d, method = "REML")
                pr <- predict(m, newdata = d, se.fit = TRUE, type = "link")
                lo <- pr$fit - z * pr$se.fit
                hi <- pr$fit + z * pr$se.fit
                inside <- (df$ftrue >= lo) & (df$ftrue <= hi)
                hit <- hit + sum(inside)
                tot <- tot + length(inside)
                se_flat <- c(se_flat, as.numeric(pr$se.fit))
            }}
            emit("coverage", hit / tot)
            emit("se_flat", se_flat)
            "#
        ),
    );
    let mgcv_coverage = r.scalar("coverage");
    let mgcv_se_flat = r.vector("se_flat");

    // rel-L2 of the pooled SE vectors (context only).
    let gam_se_flat: Vec<f64> = gam_se_by_rep.into_iter().flatten().collect();
    assert_eq!(
        gam_se_flat.len(),
        mgcv_se_flat.len(),
        "pooled SE vector length mismatch between engines"
    );
    let se_rel = relative_l2(&gam_se_flat, mgcv_se_flat);

    let gam_err = (gam_coverage - 0.95).abs();
    let mgcv_err = (mgcv_coverage - 0.95).abs();

    eprintln!(
        "gaussian s(x) CI coverage: n={n} reps={reps} sigma={sigma} \
         gam_cov={gam_coverage:.4} mgcv_cov={mgcv_coverage:.4} \
         gam_err={gam_err:.4} mgcv_err={mgcv_err:.4} se_rel_l2={se_rel:.5} (context)"
    );

    // ---- PRIMARY objective assertion: gam's pointwise CI is calibrated -----
    // Across-the-function Bayesian coverage should land near nominal. The band
    // is ±0.04 around 0.95 (i.e. empirical coverage in [0.91, 0.99]): wide
    // enough to absorb Monte-Carlo error at 60×200 = 12 000 interval checks (MC
    // SE ≈ 0.002, see the `reps` comment) and the mild representation bias of the
    // basis, tight enough that an SE that is grossly mis-scaled (variance off by a
    // constant factor) breaks it.
    assert!(
        gam_coverage >= 0.91 && gam_coverage <= 0.99,
        "gam's nominal-95% pointwise CI is mis-calibrated: empirical coverage \
         {gam_coverage:.4} (target 0.95 ± 0.04)"
    );

    // ---- SECONDARY: match-or-beat mgcv on calibration ----------------------
    // gam's distance-from-nominal must not exceed mgcv's by more than a small
    // slack (Monte-Carlo wiggle on equal data).
    assert!(
        gam_err <= mgcv_err + 0.02,
        "gam's CI coverage error {gam_err:.4} is worse than mgcv's {mgcv_err:.4} \
         by more than the 0.02 slack (gam_cov={gam_coverage:.4}, \
         mgcv_cov={mgcv_coverage:.4})"
    );
}
