pub(crate) mod active_set;
pub mod arrow_schur;
#[cfg(feature = "ceres-backend")]
pub mod ceres_backend;
pub mod estimate;
pub mod gaussian_reml;
pub mod mixture_link;
pub mod outer_strategy;
pub(crate) mod latent_cache;
pub(crate) mod persistent_warm_start;
pub mod pirls;
pub mod protocol;
pub mod riemannian;
pub mod seeding;
pub mod visualizer;
pub(crate) mod workflow;
pub mod latent_inner;
