//! Share exact decoded native operators across compacted/permuted artifact graphs.
//! Names generated by the decoder are non-wire placeholders. Meaningful names or
//! provenance are retained by leaving those operators owned. Execution, numeric
//! values, operator indices, interfaces, wire bytes and C32 remain unchanged.
use crate::artifact::Artifact;
use crate::operator_program::{Operator, OperatorBody, Provenance};
use ndarray::{Array1, Array2};
use std::{
    collections::{HashMap, hash_map::DefaultHasher},
    hash::{Hash, Hasher},
    sync::Arc,
};

pub struct DecodedOperatorInterner {
    buckets: HashMap<u64, Vec<Arc<Operator>>>,
}
fn decoded_metadata(operator: &Operator, index: usize) -> bool {
    operator.name == format!("decoded{index}") && operator.provenance == Provenance::default()
}
fn samples(len: usize, mut value: impl FnMut(usize) -> u64, state: &mut DefaultHasher) {
    len.hash(state);
    if len == 0 {
        return;
    }
    for i in 0..8 {
        // Bounded indexing, without scanning or hashing entire parameter tensors.
        let last = len - 1;
        let position = (last / 7) * i + ((last % 7) * i) / 7;
        value(position).hash(state);
    }
}
fn matrix_key(a: &Array2<f64>, state: &mut DefaultHasher) {
    a.dim().hash(state);
    samples(
        a.len(),
        |i| a[[i / a.ncols(), i % a.ncols()]].to_bits(),
        state,
    );
}
fn vector_key(a: &Array1<f64>, state: &mut DefaultHasher) {
    samples(a.len(), |i| a[i].to_bits(), state)
}
fn key(operator: &Operator) -> u64 {
    let mut state = DefaultHasher::new();
    operator.rows.hash(&mut state);
    operator.cols.hash(&mut state);
    match &operator.body {
        OperatorBody::Identity => 0_u8.hash(&mut state),
        OperatorBody::Dense {
            values,
            present,
            precision,
        } => {
            1_u8.hash(&mut state);
            precision.hash(&mut state);
            matrix_key(values, &mut state);
            present.dim().hash(&mut state);
            samples(
                present.len(),
                |i| u64::from(present[[i / present.ncols(), i % present.ncols()]]),
                &mut state,
            );
        }
        OperatorBody::LowRank {
            left,
            right,
            precision,
        } => {
            2_u8.hash(&mut state);
            precision.hash(&mut state);
            matrix_key(left, &mut state);
            matrix_key(right, &mut state)
        }
        OperatorBody::Diagonal { values, precision } => {
            3_u8.hash(&mut state);
            precision.hash(&mut state);
            vector_key(values, &mut state)
        }
    }
    state.finish()
}
fn matrix_equal(a: &Array2<f64>, b: &Array2<f64>) -> bool {
    a.dim() == b.dim() && a.iter().zip(b).all(|(x, y)| x.to_bits() == y.to_bits())
}
fn vector_equal(a: &Array1<f64>, b: &Array1<f64>) -> bool {
    a.len() == b.len() && a.iter().zip(b).all(|(x, y)| x.to_bits() == y.to_bits())
}
fn exact(operator: &Operator, base: &Operator) -> bool {
    operator.rows == base.rows
        && operator.cols == base.cols
        && match (&operator.body, &base.body) {
            (OperatorBody::Identity, OperatorBody::Identity) => true,
            (
                OperatorBody::Dense {
                    values: a,
                    present: ap,
                    precision: ac,
                },
                OperatorBody::Dense {
                    values: b,
                    present: bp,
                    precision: bc,
                },
            ) => ac == bc && ap == bp && matrix_equal(a, b),
            (
                OperatorBody::LowRank {
                    left: a,
                    right: ar,
                    precision: ac,
                },
                OperatorBody::LowRank {
                    left: b,
                    right: br,
                    precision: bc,
                },
            ) => ac == bc && matrix_equal(a, b) && matrix_equal(ar, br),
            (
                OperatorBody::Diagonal {
                    values: a,
                    precision: ac,
                },
                OperatorBody::Diagonal {
                    values: b,
                    precision: bc,
                },
            ) => ac == bc && vector_equal(a, b),
            _ => false,
        }
}
impl DecodedOperatorInterner {
    /// `native` must come from Artifact::from_bytes/decode, not the importer's
    /// named/provenanced program. No tensor clone or whole-model hash is made.
    pub fn new(native: &Artifact) -> Result<Self, String> {
        if native
            .program
            .operators
            .iter()
            .enumerate()
            .any(|(i, o)| !decoded_metadata(o, i))
        {
            return Err("operator interning requires the decoded native artifact".into());
        }
        let mut buckets: HashMap<u64, Vec<Arc<Operator>>> = HashMap::new();
        for operator in &native.program.operators {
            buckets
                .entry(key(operator))
                .or_default()
                .push(operator.clone());
        }
        Ok(Self { buckets })
    }
    /// Replace only exact wire-equivalent operators with native Arcs. The small
    /// signature is only a lookup: full bitwise equality licenses every reuse,
    /// including values outside the samples and masks/precision/interfaces.
    /// Canonical decoder labels may become those of the shared native operator;
    /// labels/provenance supplied by a caller are never discarded.
    pub fn intern(&self, candidate: &mut Artifact) -> usize {
        let mut shared = 0;
        for (index, operator) in candidate.program.operators.iter_mut().enumerate() {
            if !decoded_metadata(operator, index) {
                continue;
            }
            if let Some(base) = self
                .buckets
                .get(&key(operator))
                .and_then(|bucket| bucket.iter().find(|base| exact(operator, base)))
            {
                *operator = base.clone();
                shared += 1;
            }
        }
        shared
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        acceptance::{CostCache, structural_cost},
        operator_program::{
            Declarations, FamilyInputs, Interface, Node, OperatorProgram, Slot, SlotValues,
            exact_precision,
        },
    };
    use ndarray::array;
    fn dense(name: &str, values: Array2<f64>) -> Arc<Operator> {
        Arc::new(
            Operator::dense(
                name,
                Interface::native(values.nrows()).unwrap(),
                Interface::native(values.ncols()).unwrap(),
                values.clone(),
                exact_precision(values.iter().copied()).unwrap(),
                Provenance::native(name),
            )
            .unwrap(),
        )
    }
    fn decoded(program: &OperatorProgram) -> Artifact {
        let artifact = Artifact::native(program).unwrap();
        Artifact::from_bytes(&artifact.to_bytes().unwrap(), &program.declarations).unwrap()
    }
    #[test]
    fn compaction_permutation_share_exact_values_without_changing_bytes_cost_or_execution() {
        let values = Array2::from_shape_fn((2, 16), |(r, c)| (r * 16 + c) as f64 / 8.0);
        let a = dense("native a", values.clone());
        let unused = dense("removed native operator", &values + 1.0);
        let head = dense("head", Array2::eye(2));
        let native = OperatorProgram {
            declarations: Declarations {
                domains: vec![],
                slots: vec![Slot::Raw { width: 16 }],
                parameters: 0,
            },
            bases: vec![],
            rules: vec![],
            operators: vec![a.clone(), unused, head.clone()],
            nodes: vec![
                Node::Raw { slot: 0 },
                Node::Affine {
                    terms: vec![(0, 0)],
                    bias: None,
                },
                Node::Affine {
                    terms: vec![(1, 2)],
                    bias: None,
                },
            ],
            output: 2,
        };
        let mut changed = values;
        changed[[0, 1]] += 0.5; // outside the eight signature samples.
        let mut program = native.clone();
        program.operators = vec![head, a, dense("changed", changed)];
        program.nodes[1] = Node::Affine {
            terms: vec![(0, 1)],
            bias: None,
        };
        program.nodes[2] = Node::Affine {
            terms: vec![(1, 0)],
            bias: None,
        };
        let base = decoded(&native);
        let mut candidate = decoded(&program);
        assert_eq!(
            key(&candidate.program.operators[2]),
            key(&base.program.operators[0])
        );
        let bytes = candidate.to_bytes().unwrap();
        let cost = structural_cost(&candidate, &mut CostCache::default()).unwrap();
        let family = FamilyInputs {
            rows: 2,
            slots: vec![SlotValues::Raw(Array2::from_shape_fn((2, 16), |(r, c)| {
                (r + c) as f64 / 4.0
            }))],
            layout: None,
        };
        let before = candidate.execute(&family).unwrap().values[candidate.program.output].clone();
        assert_eq!(
            DecodedOperatorInterner::new(&base)
                .unwrap()
                .intern(&mut candidate),
            2
        );
        assert!(Arc::ptr_eq(
            &candidate.program.operators[0],
            &base.program.operators[2]
        ));
        assert!(Arc::ptr_eq(
            &candidate.program.operators[1],
            &base.program.operators[0]
        ));
        assert!(!Arc::ptr_eq(
            &candidate.program.operators[2],
            &base.program.operators[0]
        ));
        assert_eq!(candidate.to_bytes().unwrap(), bytes);
        assert_eq!(
            structural_cost(&candidate, &mut CostCache::default()).unwrap(),
            cost
        );
        assert_eq!(
            candidate.execute(&family).unwrap().values[candidate.program.output],
            before
        );
    }
    #[test]
    fn meaningful_metadata_is_preserved_and_named_import_is_not_a_decoded_pool() {
        let native = OperatorProgram {
            declarations: Declarations {
                domains: vec![],
                slots: vec![Slot::Raw { width: 2 }],
                parameters: 0,
            },
            bases: vec![],
            rules: vec![],
            operators: vec![dense("native", array![[1.0, 0.0], [0.0, 1.0]])],
            nodes: vec![
                Node::Raw { slot: 0 },
                Node::Affine {
                    terms: vec![(0, 0)],
                    bias: None,
                },
            ],
            output: 1,
        };
        assert!(DecodedOperatorInterner::new(&Artifact::native(&native).unwrap()).is_err());
        let base = decoded(&native);
        let mut candidate = decoded(&native);
        let operator = Arc::make_mut(&mut candidate.program.operators[0]);
        operator.name = "audited source".into();
        operator.provenance = Provenance::native("retained provenance");
        let before = candidate.program.operators[0].clone();
        assert_eq!(
            DecodedOperatorInterner::new(&base)
                .unwrap()
                .intern(&mut candidate),
            0
        );
        assert!(Arc::ptr_eq(&candidate.program.operators[0], &before));
        assert_eq!(candidate.program.operators[0].name, "audited source");
    }
}
