name: bench-setup
description: Shared setup for benchmark jobs
inputs:
  install-runtime-deps:
    description: "Install benchmark Python/R dependencies in the job environment"
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-bench-pip-${{ hashFiles('.github/actions/bench-setup/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-bench-pip-

    - name: Cache R user library
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.r-lib
        key: ${{ runner.os }}-bench-rlib-${{ hashFiles('.github/actions/bench-setup/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-bench-rlib-

    - name: Cache cargo artifacts
      uses: Swatinem/rust-cache@v2

    - name: Install benchmark runtime deps
      if: ${{ inputs.install-runtime-deps == 'true' }}
      shell: bash
      run: |
        mkdir -p "${R_LIBS_USER}"
        python3 --version
        Rscript --version
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install numpy pandas scikit-learn pygam lifelines scikit-survival xgboost
        Rscript -e 'install.packages(c("mgcv","jsonlite","survival","glmnet","gamlss","gamlss.dist","gamboostLSS","mboost","bamlss","brms"), repos="https://cloud.r-project.org", lib=Sys.getenv("R_LIBS_USER"), Ncpus=max(1L, parallel::detectCores()-1L))'
