//! Sufficient computational state over finite native intervention responses
//! (#2951, P13).
//!
//! # The quotient
//!
//! A computational state `h ∈ ℝᵈ` (a per-input coordinate, never a
//! parameter-family label) is followed by a declared finite family of permitted
//! futures `r_1..r_K`. Each future is a native execution: transitions under
//! declared interventions, then a readout. Two states are equivalent, `h ∼ h'`,
//! iff every permitted future agrees on them. A chart `E` is a sufficient state
//! iff it never merges two inequivalent states.
//!
//! * **Descent.** If the family is closed under prepending a transition `T_a`
//!   (`r ∈ F ⇒ r∘T_a ∈ F`), then `h ∼ h'` gives
//!   `r(T_a h) = (r∘T_a)(h) = (r∘T_a)(h') = r(T_a h')`. So `T_a` descends, and a
//!   minimal sufficient chart satisfies `E_next∘T_a = G_a∘E`.
//! * **Local dimension.** Let `R = (r_1..r_K)` *generate* the family: every
//!   permitted future is a function of `R`. Where `R` has constant rank `k` on a
//!   neighbourhood of `h`, the constant-rank theorem makes the fibres of `R` near
//!   `h` submanifolds of dimension `d − k` and the quotient a `k`-manifold, so `k`
//!   is the local minimal dimension. Both hypotheses are load-bearing.
//!   * A family that does not generate can have a smaller rank. Observing `a` of
//!     `(a, b)` under `T(a, b) = (a + b, b)` has rank 1; adding `a∘T` gives 2.
//!   * At a point where the rank drops (`o(h) = h²` at `h = 0`) the rank there
//!     is not the local dimension. For an analytic response map on a connected
//!     domain the generic rank is attained arbitrarily close to such a point, so
//!     no constant-rank chart exists there; a merely smooth map can keep a lower
//!     rank on an open set. A resolved rank is only a lower bound, so falling
//!     short of the generic rank at a band does not by itself certify a drop.
//! * **Fibres are global.** The rank at `h` tests local injectivity only.
//!   `o(h) = h²` has full rank at `h = ±1` yet merges them, and the future
//!   `h ↦ h + 1` separates them (`0` against `4`). [`fiber_test`] compares each
//!   stated native state with its section representative `D(E(h))`, which lies in
//!   the same fibre of `E`. Checking responses on decoded states `h = D(z)`
//!   compares each state with itself: a check on decoder sections does not test
//!   fibres, and the test refuses a sample on which every comparison is of that
//!   kind.
//!
//! # Two contracts that are not one
//!
//! * The **quotient contract** `E'∘T = g∘E` ([`QuotientContract`]) says the code
//!   descends. It is checked at native states, off any section.
//! * The **realization contract** `T∘D = D'∘g` ([`RealizationContract`]) says
//!   decoded representatives are carried to decoded representatives. It is
//!   checked at codes, on the section.
//!
//! Neither implies the other.
//! * `T(z, n) = (z, n + 1)` with only `z` observed satisfies the quotient
//!   contract with `E = E' = (z, n) ↦ z` and `g = id`. No section `D = D'`
//!   realizes it, because `T(D z)` has fibre coordinate one more than `D(z)`.
//! * `T(z, n) = (z + n, n)` fixes the section `D(z) = (z, 0)`, so the realization
//!   contract holds with `g = id`. The quotient contract fails at every state with
//!   `n ≠ 0`. With `E'∘D' = id` a realization gives `E'∘T∘D = g`, a statement on
//!   the section only.
//!
//! # Linear quotient
//!
//! For linear readouts `M_k` and transitions `T_a`, the family generated by
//! prepending transitions is `{M_k T_w}`. Its minimal sufficient state is the
//! projection onto the observable subspace: the smallest row space that contains
//! the readout rows and is invariant under `v ↦ v T_a`. [`LinearStateQuotient`]
//! closes that subspace, descends each transition to `G_a = Q T_a Qᵀ`, and
//! measures three different defects as spectral-norm bounds that hold at every
//! state: readout sufficiency, the quotient contract, and the realization
//! contract of the decoder `Qᵀ`. Invariance under `v ↦ v T_a` does not imply
//! invariance under `T_a`, so a closed chart can descend exactly while its
//! realization fails.
//!
//! # Decisions
//!
//! Every native map reports a derived roundoff bound with its value
//! ([`Evaluation`]), so every verdict separates what the arithmetic resolved from
//! what it did not.
//! * A violation or separation is reported only when a computed defect exceeds
//!   the combined bounds.
//! * Otherwise the result is a uniform bound over the stated finite states or
//!   codes, roundoff included. It is never an exact equality.
//! * A rank counts the singular values above
//!   [`gam_linalg::roundoff::factor_singular_band`] plus the Jacobians' formation
//!   bound. That is a certified lower bound on the exact rank, and it is exact
//!   only where it reaches `min(rows, d)`.
//! * The fidelity tolerance is a declared experiment input with no default.
//! * Every verdict converts to the shared
//!   [`EvidenceStatus`](super::supports::EvidenceStatus). A violation or a
//!   separation is a counterexample, a bound over the stated items is a uniform
//!   bound, an unresolved separation, rank or norm is unresolved, and a rank at
//!   its ceiling is exact. A verdict decides each evaluated item through the
//!   status supports.rs owns (its rounded bounds and threshold predicates), the
//!   derivation the counterexample constructor reads. So a verdict and its
//!   evidence never disagree, and no copy of that arithmetic lives here.

use std::fmt;

use gam_linalg::faer_ndarray::{FaerLinalgError, FaerSvd};
use gam_linalg::roundoff::{accumulation_band, accumulation_growth, factor_singular_band};
use ndarray::{Array1, Array2, ArrayView1, ArrayView2, s};

use super::supports::{EvidenceStatus, EvidenceStatusError, ExactBasis, Extremum};

/// A computed value with a derived bound on its roundoff.
#[derive(Clone, Debug)]
pub struct Evaluation {
    /// The computed value.
    pub value: Array1<f64>,
    /// Bound on `‖value − f(x)‖∞` over every exact input `x` within the
    /// evaluation's input roundoff of the supplied input.
    pub roundoff: f64,
}

/// A native computation between coordinate spaces: a transition, a readout, a
/// chart's encoder or decoder, or a descended map. It owns its error model.
pub trait NativeMap {
    /// Dimension of the input coordinates.
    fn input_dimension(&self) -> usize;
    /// Dimension of the output coordinates.
    fn output_dimension(&self) -> usize;
    /// The computed value at `input`, with a bound on its sup-norm distance to
    /// the exact map's value at every input within `input_roundoff` (sup norm)
    /// of `input`.
    fn evaluate(
        &self,
        input: ArrayView1<'_, f64>,
        input_roundoff: f64,
    ) -> Result<Evaluation, StateError>;
}

/// An analytic Jacobian with a bound on its formation error.
#[derive(Clone, Debug)]
pub struct JacobianEvaluation {
    /// `output_dimension × input_dimension`.
    pub matrix: Array2<f64>,
    /// Bound on the spectral norm of `matrix` minus the exact Jacobian at the
    /// supplied input.
    pub roundoff: f64,
}

/// A native map with an analytic Jacobian.
pub trait DifferentiableNativeMap: NativeMap {
    /// The Jacobian at `input`.
    fn jacobian(&self, input: ArrayView1<'_, f64>) -> Result<JacobianEvaluation, StateError>;
}

/// What a state-check verdict ranges over, as an evidence-status domain.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StateDomain {
    /// The stated native states, by row.
    States { count: usize },
    /// The stated codes, by row.
    Codes { count: usize },
    /// The tested states of a fibre test times its futures. Vacuous states lay on
    /// the section and are not in the family.
    FiberPairs {
        tested_states: usize,
        vacuous_states: usize,
        futures: usize,
    },
    /// Every state of `ℝᵈ` through a spectral norm, so a bound scales with the
    /// state's norm.
    UnitStates { dimension: usize },
}

/// A stated native state, by row: the witness of a quotient-contract verdict.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StateRow(pub usize);

/// A stated code, by row: the witness of a realization-contract verdict.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CodeRow(pub usize);

/// A fibre-test witness: a stated state, its section representative, the future
/// compared on them, and the resolution at which the chart merges the pair.
#[derive(Clone, Debug, PartialEq)]
pub struct FiberWitness {
    pub state: usize,
    pub future: usize,
    pub representative: Array1<f64>,
    pub merge_bound: f64,
}

/// The quotient contract `E'∘T = g∘E`: the code of the transitioned state is the
/// descended code.
pub struct QuotientContract<'a> {
    /// `T : H → H'`.
    pub transition: &'a dyn NativeMap,
    /// `E : H → Z`.
    pub encoder: &'a dyn NativeMap,
    /// `E' : H' → Z'`.
    pub next_encoder: &'a dyn NativeMap,
    /// `g : Z → Z'`.
    pub descended: &'a dyn NativeMap,
}

/// What [`QuotientContract::check`] resolved over the stated states.
#[derive(Clone, Debug, PartialEq)]
pub enum QuotientContractVerdict {
    /// At `state`, `‖E'(T h) − g(E h)‖∞ = defect` exceeds the combined roundoff
    /// of both sides: the code does not descend. This is the state with the
    /// largest excess.
    Violated {
        state: usize,
        defect: f64,
        roundoff: f64,
    },
    /// At every stated state the exact defect is at most `bound`, roundoff
    /// included. `roundoff` is the largest combined roundoff, kept for audit, and
    /// `states` counts the stated states.
    Bounded {
        bound: f64,
        roundoff: f64,
        states: usize,
    },
}

impl QuotientContractVerdict {
    /// The verdict as the evidence status of `sup_h ‖E'(T h) − g(E h)‖∞` over the
    /// stated states.
    pub fn evidence(&self) -> Result<EvidenceStatus<StateRow, StateDomain>, EvidenceStatusError> {
        match *self {
            Self::Violated {
                state,
                defect,
                roundoff,
            } => EvidenceStatus::counterexample(defect, roundoff, 0.0, StateRow(state)),
            Self::Bounded {
                bound,
                roundoff,
                states,
            } => EvidenceStatus::uniform_bound(bound, roundoff, StateDomain::States { count: states }),
        }
    }
}

impl QuotientContract<'_> {
    /// Check the contract at native states, the rows of `states`.
    pub fn check(
        &self,
        states: ArrayView2<'_, f64>,
    ) -> Result<QuotientContractVerdict, StateError> {
        let dimension = self.transition.input_dimension();
        require_dimension(
            self.encoder.input_dimension(),
            dimension,
            "quotient contract: E and T share a state space",
        )?;
        require_dimension(
            self.next_encoder.input_dimension(),
            self.transition.output_dimension(),
            "quotient contract: T into E'",
        )?;
        require_dimension(
            self.descended.input_dimension(),
            self.encoder.output_dimension(),
            "quotient contract: E into g",
        )?;
        require_dimension(
            self.descended.output_dimension(),
            self.next_encoder.output_dimension(),
            "quotient contract: E' and g share a code space",
        )?;
        require_sample(states, dimension, "quotient contract: states")?;
        let mut record = DefectRecord::new();
        for (index, state) in states.rows().into_iter().enumerate() {
            let moved = evaluated(self.transition, state, 0.0, "quotient contract: T(h)")?;
            let after = evaluated(
                self.next_encoder,
                moved.value.view(),
                moved.roundoff,
                "quotient contract: E'(T h)",
            )?;
            let code = evaluated(self.encoder, state, 0.0, "quotient contract: E(h)")?;
            let descended = evaluated(
                self.descended,
                code.value.view(),
                code.roundoff,
                "quotient contract: g(E h)",
            )?;
            record.observe(
                index,
                sup_distance(after.value.view(), descended.value.view()),
                after.roundoff + descended.roundoff,
            )?;
        }
        Ok(match record.violation {
            Some((state, defect, roundoff, _)) => QuotientContractVerdict::Violated {
                state,
                defect,
                roundoff,
            },
            None => QuotientContractVerdict::Bounded {
                bound: record.bound,
                roundoff: record.roundoff,
                states: record.count,
            },
        })
    }
}

/// The realization contract `T∘D = D'∘g`: decoded representatives are carried
/// to decoded representatives.
pub struct RealizationContract<'a> {
    /// `T : H → H'`.
    pub transition: &'a dyn NativeMap,
    /// `D : Z → H`.
    pub decoder: &'a dyn NativeMap,
    /// `D' : Z' → H'`.
    pub next_decoder: &'a dyn NativeMap,
    /// `g : Z → Z'`.
    pub descended: &'a dyn NativeMap,
}

/// What [`RealizationContract::check`] resolved over the stated codes.
#[derive(Clone, Debug, PartialEq)]
pub enum RealizationContractVerdict {
    /// At `code`, `‖T(D z) − D'(g z)‖∞ = defect` exceeds the combined roundoff
    /// of both sides: the decoded representative is not carried to the decoded
    /// representative. This is the code with the largest excess.
    Violated {
        code: usize,
        defect: f64,
        roundoff: f64,
    },
    /// At every stated code the exact defect is at most `bound`, roundoff
    /// included. `roundoff` is the largest combined roundoff, kept for audit, and
    /// `codes` counts the stated codes.
    Bounded {
        bound: f64,
        roundoff: f64,
        codes: usize,
    },
}

impl RealizationContractVerdict {
    /// The verdict as the evidence status of `sup_z ‖T(D z) − D'(g z)‖∞` over the
    /// stated codes.
    pub fn evidence(&self) -> Result<EvidenceStatus<CodeRow, StateDomain>, EvidenceStatusError> {
        match *self {
            Self::Violated {
                code,
                defect,
                roundoff,
            } => EvidenceStatus::counterexample(defect, roundoff, 0.0, CodeRow(code)),
            Self::Bounded {
                bound,
                roundoff,
                codes,
            } => EvidenceStatus::uniform_bound(bound, roundoff, StateDomain::Codes { count: codes }),
        }
    }
}

impl RealizationContract<'_> {
    /// Check the contract at codes, the rows of `codes`.
    pub fn check(
        &self,
        codes: ArrayView2<'_, f64>,
    ) -> Result<RealizationContractVerdict, StateError> {
        let dimension = self.decoder.input_dimension();
        require_dimension(
            self.descended.input_dimension(),
            dimension,
            "realization contract: D and g share a code space",
        )?;
        require_dimension(
            self.transition.input_dimension(),
            self.decoder.output_dimension(),
            "realization contract: D into T",
        )?;
        require_dimension(
            self.next_decoder.input_dimension(),
            self.descended.output_dimension(),
            "realization contract: g into D'",
        )?;
        require_dimension(
            self.next_decoder.output_dimension(),
            self.transition.output_dimension(),
            "realization contract: T and D' share a state space",
        )?;
        require_sample(codes, dimension, "realization contract: codes")?;
        let mut record = DefectRecord::new();
        for (index, code) in codes.rows().into_iter().enumerate() {
            let decoded = evaluated(self.decoder, code, 0.0, "realization contract: D(z)")?;
            let moved = evaluated(
                self.transition,
                decoded.value.view(),
                decoded.roundoff,
                "realization contract: T(D z)",
            )?;
            let descended = evaluated(self.descended, code, 0.0, "realization contract: g(z)")?;
            let represented = evaluated(
                self.next_decoder,
                descended.value.view(),
                descended.roundoff,
                "realization contract: D'(g z)",
            )?;
            record.observe(
                index,
                sup_distance(moved.value.view(), represented.value.view()),
                moved.roundoff + represented.roundoff,
            )?;
        }
        Ok(match record.violation {
            Some((code, defect, roundoff, _)) => RealizationContractVerdict::Violated {
                code,
                defect,
                roundoff,
            },
            None => RealizationContractVerdict::Bounded {
                bound: record.bound,
                roundoff: record.roundoff,
                codes: record.count,
            },
        })
    }
}

/// A candidate sufficient state: an encoder together with a section of it.
pub struct StateChart<'a> {
    /// `E : H → Z`.
    pub encoder: &'a dyn NativeMap,
    /// `D : Z → H` with `E∘D = id` on the codes the encoder produces.
    pub decoder: &'a dyn NativeMap,
}

/// What [`fiber_test`] resolved over the stated states and futures.
#[derive(Clone, Debug, PartialEq)]
pub enum FiberVerdict {
    /// The chart maps `witness.state` and its section representative within
    /// `witness.merge_bound` of each other in code space, yet `witness.future`
    /// separates them by `distance`, and `distance − roundoff` exceeds the
    /// declared `fidelity`. This refutes the chart as a sufficient state at
    /// resolution `merge_bound`: no readout descended through the chart with a
    /// modulus of continuity `ω` satisfying `ω(merge_bound) < distance − roundoff`
    /// reproduces the future. In particular no readout Lipschitz below
    /// `(distance − roundoff) / merge_bound` does. Exact non-sufficiency needs an
    /// exact merge. This is the pair with the largest certified separation.
    Separated {
        witness: FiberWitness,
        distance: f64,
        roundoff: f64,
        fidelity: f64,
    },
    /// At every tested state every future agrees with its value at the
    /// representative within `separation_upper_bound`, roundoff included, and
    /// that bound is within the declared fidelity. `vacuous_states` lay on the
    /// section and tested nothing. `roundoff` is the largest combined roundoff,
    /// kept for audit.
    WithinFidelity {
        tested_states: usize,
        vacuous_states: usize,
        futures: usize,
        separation_upper_bound: f64,
        roundoff: f64,
    },
    /// No separation is certified above the declared fidelity, but the largest
    /// separation's roundoff interval contains it. `witness` attains
    /// `separation_lower_bound`.
    Unresolved {
        tested_states: usize,
        vacuous_states: usize,
        futures: usize,
        separation_lower_bound: f64,
        separation_upper_bound: f64,
        witness: FiberWitness,
    },
}

impl FiberVerdict {
    /// The verdict as the evidence status of `sup ‖r_k(h) − r_k(D(E h))‖∞` over
    /// the tested states and futures.
    pub fn evidence(
        &self,
    ) -> Result<EvidenceStatus<FiberWitness, StateDomain>, EvidenceStatusError> {
        match self {
            Self::Separated {
                witness,
                distance,
                roundoff,
                fidelity,
            } => EvidenceStatus::counterexample(*distance, *roundoff, *fidelity, witness.clone()),
            Self::WithinFidelity {
                tested_states,
                vacuous_states,
                futures,
                separation_upper_bound,
                roundoff,
            } => EvidenceStatus::uniform_bound(
                *separation_upper_bound,
                *roundoff,
                StateDomain::FiberPairs {
                    tested_states: *tested_states,
                    vacuous_states: *vacuous_states,
                    futures: *futures,
                },
            ),
            Self::Unresolved {
                tested_states,
                vacuous_states,
                futures,
                separation_lower_bound,
                separation_upper_bound,
                witness,
            } => EvidenceStatus::unresolved(
                *separation_lower_bound,
                *separation_upper_bound,
                Extremum::Supremum,
                Some(witness.clone()),
                StateDomain::FiberPairs {
                    tested_states: *tested_states,
                    vacuous_states: *vacuous_states,
                    futures: *futures,
                },
            ),
        }
    }
}

/// Test whether `chart` is a sufficient state for `futures` at the stated native
/// states, the rows of `states`.
///
/// Each state `h` is compared with its section representative `h̃ = D(E(h))`,
/// which the chart cannot tell apart from `h`, on every future. `fidelity` is
/// the declared largest sup-norm response difference that counts as agreement.
///
/// Refusals:
/// * [`StateError::NotASection`] when `E(D(E h))` differs from `E(h)` by more
///   than the arithmetic explains. Then `h̃` is not in the fibre of `h`, so a
///   separation would say nothing about `E`.
/// * [`StateError::VacuousFiberTest`] when every state lies on the section
///   within the decoder's roundoff, so every comparison is of a state with
///   itself.
pub fn fiber_test(
    chart: &StateChart<'_>,
    futures: &[&dyn NativeMap],
    states: ArrayView2<'_, f64>,
    fidelity: f64,
) -> Result<FiberVerdict, StateError> {
    if !fidelity.is_finite() || fidelity < 0.0 {
        return Err(StateError::InvalidFidelity { value: fidelity });
    }
    let dimension = chart.encoder.input_dimension();
    require_dimension(
        chart.decoder.input_dimension(),
        chart.encoder.output_dimension(),
        "fiber test: encoder into decoder",
    )?;
    require_dimension(
        chart.decoder.output_dimension(),
        dimension,
        "fiber test: decoder into the state space",
    )?;
    if futures.is_empty() {
        return Err(StateError::EmptyFamily {
            context: "fiber test: futures",
        });
    }
    for future in futures {
        require_dimension(
            future.input_dimension(),
            dimension,
            "fiber test: future on the state space",
        )?;
    }
    require_sample(states, dimension, "fiber test: states")?;
    let mut tested_states = 0;
    let mut vacuous_states = 0;
    let mut largest_upper = 0.0_f64;
    let mut largest_roundoff = 0.0_f64;
    // The pair whose evaluated separation has the largest certified lower bound:
    // if it does not refute the fidelity, no pair does.
    let mut strongest: Option<(FiberWitness, f64, f64, EvidenceStatus<(), ()>)> = None;
    for (index, state) in states.rows().into_iter().enumerate() {
        let code = evaluated(chart.encoder, state, 0.0, "fiber test: E(h)")?;
        let representative =
            evaluated(chart.decoder, code.value.view(), 0.0, "fiber test: D(E h)")?;
        let round_trip = evaluated(
            chart.encoder,
            representative.value.view(),
            representative.roundoff,
            "fiber test: E(D(E h))",
        )?;
        let code_defect = sup_distance(round_trip.value.view(), code.value.view());
        if code_defect > round_trip.roundoff {
            return Err(StateError::NotASection {
                state: index,
                code_defect,
                roundoff: round_trip.roundoff,
            });
        }
        if sup_distance(state, representative.value.view()) <= representative.roundoff {
            vacuous_states += 1;
            continue;
        }
        tested_states += 1;
        let merge_bound = code.roundoff + code_defect + round_trip.roundoff;
        for (future_index, future) in futures.iter().enumerate() {
            let native = evaluated(*future, state, 0.0, "fiber test: r(h)")?;
            let represented = evaluated(
                *future,
                representative.value.view(),
                0.0,
                "fiber test: r(D(E h))",
            )?;
            let distance = sup_distance(native.value.view(), represented.value.view());
            let roundoff = native.roundoff + represented.roundoff;
            let separation = evaluated_defect(distance, roundoff)?;
            largest_upper = largest_upper.max(certified_upper(&separation));
            largest_roundoff = largest_roundoff.max(roundoff);
            let larger = match &strongest {
                Some((_, _, _, best)) => certified_lower(&separation) > certified_lower(best),
                None => true,
            };
            if larger {
                strongest = Some((
                    FiberWitness {
                        state: index,
                        future: future_index,
                        representative: representative.value.clone(),
                        merge_bound,
                    },
                    distance,
                    roundoff,
                    separation,
                ));
            }
        }
    }
    let (witness, distance, roundoff, separation) = match strongest {
        Some(strongest) => strongest,
        None => {
            return Err(StateError::VacuousFiberTest {
                states: vacuous_states,
            });
        }
    };
    let futures = futures.len();
    Ok(if separation.refutes_at_most(fidelity) {
        FiberVerdict::Separated {
            witness,
            distance,
            roundoff,
            fidelity,
        }
    } else if largest_upper <= fidelity {
        FiberVerdict::WithinFidelity {
            tested_states,
            vacuous_states,
            futures,
            separation_upper_bound: largest_upper,
            roundoff: largest_roundoff,
        }
    } else {
        FiberVerdict::Unresolved {
            tested_states,
            vacuous_states,
            futures,
            separation_lower_bound: certified_lower(&separation).max(0.0),
            separation_upper_bound: largest_upper,
            witness,
        }
    })
}

/// The local quotient at one state, read off the stacked response Jacobian.
#[derive(Clone, Debug)]
pub struct LocalQuotient {
    /// Singular values of the stacked Jacobian, descending.
    pub singular_values: Vec<f64>,
    /// The SVD's backward-error band plus the stacked Jacobians' formation
    /// bound.
    pub band: f64,
    /// Number of singular values above `band`: a certified lower bound on the
    /// exact rank at the state.
    pub resolved_rank: usize,
    /// `min(response rows, d)`, the most the rank can be.
    pub rank_ceiling: usize,
    /// Orthonormal rows (`resolved_rank × d`) spanning the state directions the
    /// futures resolve. To first order their orthogonal complement is tangent to
    /// the fibre.
    pub observed_directions: Array2<f64>,
}

/// The local dimension a state's resolved rank supports.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum LocalDimension {
    /// The resolved rank reaches its ceiling, so the rank is exact at the state.
    /// By lower semicontinuity it is constant on a neighbourhood. For a
    /// generating family this is the local minimal dimension.
    Certified(usize),
    /// The resolved rank equals the sample's generic rank but is below its
    /// ceiling. The exact rank is at least this; a larger one hidden below the
    /// band is not excluded.
    AtLeast(usize),
    /// The rank at this state is not resolved up to the sample's generic rank at
    /// this band: `largest_unresolved_singular_value ≤ band`. Either the exact
    /// rank drops here, or a singular value sits below the band. The check cannot
    /// tell which, so this is not a certificate of a singular point. Where the
    /// exact rank does drop and the response map is analytic on a connected
    /// domain, the generic rank is attained arbitrarily close, so the rank is not
    /// constant near the state and no constant-rank chart exists there. A merely
    /// smooth map can keep a lower rank on an open set.
    BelowGeneric {
        resolved_rank: usize,
        generic_rank: usize,
        largest_unresolved_singular_value: f64,
        band: f64,
    },
}

/// The resolved ranks of a response family over stated states.
#[derive(Clone, Debug)]
pub struct ConstantRankCheck {
    /// One local quotient per stated state, in row order.
    pub states: Vec<LocalQuotient>,
    /// The largest resolved rank over the stated states: a certified lower
    /// bound on the family's largest rank on them.
    pub generic_rank: usize,
}

impl ConstantRankCheck {
    /// The local dimension at stated state `state`, relative to the sample's
    /// generic rank.
    pub fn local_dimension(&self, state: usize) -> Option<LocalDimension> {
        self.states.get(state).map(|local| {
            if local.resolved_rank < self.generic_rank {
                LocalDimension::BelowGeneric {
                    resolved_rank: local.resolved_rank,
                    generic_rank: self.generic_rank,
                    largest_unresolved_singular_value: local
                        .singular_values
                        .get(local.resolved_rank)
                        .copied()
                        .unwrap_or(0.0),
                    band: local.band,
                }
            } else if local.resolved_rank == local.rank_ceiling {
                LocalDimension::Certified(local.resolved_rank)
            } else {
                LocalDimension::AtLeast(local.resolved_rank)
            }
        })
    }

    /// The exact rank of the stacked Jacobian at stated state `state`. At its
    /// ceiling the certified lower bound (Weyl) collapses onto the ceiling, so the
    /// rank is fixed by that identity and reported as [`ExactBasis::Algebraic`].
    /// Otherwise only the resolved lower bound and the ceiling are derived.
    pub fn rank_evidence(
        &self,
        state: usize,
    ) -> Option<Result<EvidenceStatus<StateRow, StateDomain>, EvidenceStatusError>> {
        self.states.get(state).map(|local| {
            if local.resolved_rank == local.rank_ceiling {
                EvidenceStatus::exact(
                    local.resolved_rank as f64,
                    0.0,
                    ExactBasis::Algebraic,
                    Some(StateRow(state)),
                    StateDomain::States { count: 1 },
                )
            } else {
                EvidenceStatus::unresolved(
                    local.resolved_rank as f64,
                    local.rank_ceiling as f64,
                    Extremum::Supremum,
                    None,
                    StateDomain::States { count: 1 },
                )
            }
        })
    }
}

/// Resolve the rank of the stacked Jacobian of `futures` at each stated state,
/// the rows of `states`.
///
/// This is the rank of the family as stated. It is the local minimal dimension
/// of the permitted family only if the stated futures generate it, and only at
/// states where [`LocalDimension::Certified`] holds. The check forms the stacked
/// `response rows × d` Jacobian of each state and its thin SVD.
pub fn constant_rank_check(
    futures: &[&dyn DifferentiableNativeMap],
    states: ArrayView2<'_, f64>,
) -> Result<ConstantRankCheck, StateError> {
    let first = futures.first().ok_or(StateError::EmptyFamily {
        context: "constant rank: futures",
    })?;
    let dimension = first.input_dimension();
    for future in futures {
        require_dimension(
            future.input_dimension(),
            dimension,
            "constant rank: future on the state space",
        )?;
    }
    require_sample(states, dimension, "constant rank: states")?;
    let rows: usize = futures.iter().map(|future| future.output_dimension()).sum();
    if rows == 0 {
        return Err(StateError::EmptyFamily {
            context: "constant rank: responses",
        });
    }
    let mut locals = Vec::with_capacity(states.nrows());
    for state in states.rows() {
        let mut stacked = Array2::<f64>::zeros((rows, dimension));
        let mut formation_squared = 0.0_f64;
        let mut offset = 0;
        for future in futures {
            let jacobian = future.jacobian(state)?;
            let height = future.output_dimension();
            if jacobian.matrix.dim() != (height, dimension) {
                return Err(StateError::DimensionMismatch {
                    context: "constant rank: Jacobian shape",
                    expected: height * dimension,
                    found: jacobian.matrix.len(),
                });
            }
            if !jacobian.roundoff.is_finite()
                || jacobian.roundoff < 0.0
                || jacobian.matrix.iter().any(|value| !value.is_finite())
            {
                return Err(StateError::NonFinite {
                    context: "constant rank: Jacobian",
                });
            }
            stacked
                .slice_mut(s![offset..offset + height, ..])
                .assign(&jacobian.matrix);
            formation_squared += jacobian.roundoff * jacobian.roundoff;
            offset += height;
        }
        // The spectral norm of a stacked error is at most the root sum of the
        // blocks' squared spectral norms.
        locals.push(resolve_stacked_factor(&stacked, formation_squared.sqrt())?);
    }
    let generic_rank = locals
        .iter()
        .map(|local| local.resolved_rank)
        .max()
        .unwrap_or(0);
    Ok(ConstantRankCheck {
        states: locals,
        generic_rank,
    })
}

/// Resolve the rank and observed directions of a stacked factor whose exact value
/// lies within `formation` of `stacked` in spectral norm. A Frobenius bound on the
/// entrywise error is valid. The band is [`factor_singular_band`] plus
/// `formation`. [`constant_rank_check`] reads this resolver for stacked response
/// Jacobians. A caller whose factor is not the Jacobian of one native map, such as
/// a metric's weighted factor, calls it directly, so [`LocalQuotient`] has one
/// owner.
pub fn resolve_stacked_factor(
    stacked: &Array2<f64>,
    formation: f64,
) -> Result<LocalQuotient, StateError> {
    let (rows, cols) = stacked.dim();
    if rows == 0 || cols == 0 {
        return Err(StateError::EmptyFamily {
            context: "stacked factor",
        });
    }
    if !formation.is_finite() || stacked.iter().any(|value| !value.is_finite()) {
        return Err(StateError::NonFinite {
            context: "stacked factor",
        });
    }
    if formation < 0.0 {
        return Err(StateError::NegativeBound {
            context: "stacked factor: formation",
            value: formation,
        });
    }
    let resolution = resolved_row_space(stacked, formation, "stacked factor")?;
    Ok(LocalQuotient {
        singular_values: resolution.singular_values,
        band: resolution.band,
        resolved_rank: resolution.rank,
        rank_ceiling: rows.min(cols),
        observed_directions: resolution.rows,
    })
}

/// Bounds on the spectral norm of an exact matrix, read off its computed value.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpectralNormBounds {
    /// `max(0, σ̂₁ − band)`. A positive value certifies a nonzero exact matrix.
    pub lower: f64,
    /// `σ̂₁ + band`. The exact norm is at most this.
    pub upper: f64,
}

impl SpectralNormBounds {
    /// The bounds as the evidence status of `sup_{‖h‖₂ = 1} ‖R h‖₂` for the
    /// measured residual `R` on `ℝᵈ`.
    pub fn evidence(
        &self,
        dimension: usize,
    ) -> Result<EvidenceStatus<Array1<f64>, StateDomain>, EvidenceStatusError> {
        EvidenceStatus::unresolved(
            self.lower,
            self.upper,
            Extremum::Supremum,
            None,
            StateDomain::UnitStates { dimension },
        )
    }
}

/// A linear sufficient state `E(h) = Q h` for linear readouts `M_k` under linear
/// transitions `T_a`, with its descended maps and measured contract bounds.
///
/// Every bound holds at every state for the supplied matrices, scaled by the
/// state's norm:
/// * `‖M_k h − Ψ_k Q h‖ ≤ readout_bounds[k].upper · ‖h‖₂` with `Ψ_k = M_k Qᵀ`:
///   each readout is a function of the chart.
/// * `‖Q T_a h − G_a Q h‖ ≤ quotient_bounds[a].upper · ‖h‖₂` with
///   `G_a = Q T_a Qᵀ`: the quotient contract `E∘T_a = G_a∘E`.
/// * `‖T_a Qᵀ z − Qᵀ G_a z‖ ≤ realization_bounds[a].upper · ‖z‖₂`: the
///   realization contract for the decoder `D = Qᵀ`, which is a section of `Q`
///   to within `section_bounds`.
#[derive(Clone, Debug)]
pub struct LinearStateQuotient {
    /// `Q`, `r × d`.
    pub chart: Array2<f64>,
    /// `Ψ_k = M_k Qᵀ`, `p_k × r`.
    pub readout_maps: Vec<Array2<f64>>,
    /// `G_a = Q T_a Qᵀ`, `r × r`.
    pub descended: Vec<Array2<f64>>,
    /// `‖M_k − Ψ_k Q‖₂`.
    pub readout_bounds: Vec<SpectralNormBounds>,
    /// `‖Q T_a − G_a Q‖₂`.
    pub quotient_bounds: Vec<SpectralNormBounds>,
    /// `‖T_a Qᵀ − Qᵀ G_a‖₂`.
    pub realization_bounds: Vec<SpectralNormBounds>,
    /// `‖Q Qᵀ − I_r‖₂`.
    pub section_bounds: SpectralNormBounds,
}

impl LinearStateQuotient {
    /// The row span of the readouts closed under the transitions (the observable
    /// subspace), measured.
    ///
    /// Starting from the resolved row span of the stacked readouts, each step
    /// appends the chart's rows moved by every transition and resolves the stack
    /// again. The resolved dimension grows at every step that does not stop and
    /// cannot exceed `d`, so the closure ends without an iteration cap. A rank the
    /// band misjudges is not hidden: it surfaces in the measured quotient bounds.
    /// The number of chart rows is not a certified dimension, because each step's
    /// band leaves out the angle error of the previous step's singular vectors.
    /// The measured bounds are the certificate.
    pub fn close(
        readouts: &[ArrayView2<'_, f64>],
        transitions: &[ArrayView2<'_, f64>],
    ) -> Result<Self, StateError> {
        let dimension = linear_family_dimension(readouts, transitions)?;
        let rows: usize = readouts.iter().map(|readout| readout.nrows()).sum();
        let mut stacked = Array2::<f64>::zeros((rows, dimension));
        let mut offset = 0;
        for readout in readouts {
            stacked
                .slice_mut(s![offset..offset + readout.nrows(), ..])
                .assign(readout);
            offset += readout.nrows();
        }
        let mut chart = resolved_row_space(&stacked, 0.0, "linear quotient: readout rows")?.rows;
        loop {
            let rank = chart.nrows();
            if rank == 0 || rank == dimension || transitions.is_empty() {
                break;
            }
            let mut candidate =
                Array2::<f64>::zeros(((transitions.len() + 1) * rank, dimension));
            candidate.slice_mut(s![..rank, ..]).assign(&chart);
            let absolute_chart = chart.mapv(f64::abs);
            let mut formation_squared = 0.0_f64;
            for (index, transition) in transitions.iter().enumerate() {
                let start = (index + 1) * rank;
                candidate
                    .slice_mut(s![start..start + rank, ..])
                    .assign(&chart.dot(transition));
                formation_squared += absolute_chart
                    .dot(&transition.mapv(f64::abs))
                    .iter()
                    .map(|&magnitude| accumulation_band(dimension, magnitude).powi(2))
                    .sum::<f64>();
            }
            let next = resolved_row_space(
                &candidate,
                formation_squared.sqrt(),
                "linear quotient: closure step",
            )?;
            if next.rank <= rank {
                break;
            }
            chart = next.rows;
        }
        Self::measure(chart, readouts, transitions)
    }

    /// Measure a declared chart `Q` (`r × d`) against the readouts and
    /// transitions.
    pub fn measure(
        chart: Array2<f64>,
        readouts: &[ArrayView2<'_, f64>],
        transitions: &[ArrayView2<'_, f64>],
    ) -> Result<Self, StateError> {
        let dimension = linear_family_dimension(readouts, transitions)?;
        require_dimension(chart.ncols(), dimension, "linear quotient: chart columns")?;
        if chart.iter().any(|value| !value.is_finite()) {
            return Err(StateError::NonFinite {
                context: "linear quotient: chart",
            });
        }
        let rank = chart.nrows();
        let section = chart.t();
        let absolute_chart = chart.mapv(f64::abs);
        let absolute_section = absolute_chart.t();

        let section_residual = &chart.dot(&section) - &Array2::<f64>::eye(rank);
        let section_band = entrywise_band_norm(
            absolute_chart
                .dot(&absolute_section)
                .mapv(|magnitude| accumulation_band(dimension + 1, magnitude + 1.0)),
        );
        let section_bounds =
            spectral_norm_bounds(&section_residual, section_band, "linear quotient: section")?;

        let mut readout_maps = Vec::with_capacity(readouts.len());
        let mut readout_bounds = Vec::with_capacity(readouts.len());
        for readout in readouts {
            let map = readout.dot(&section);
            let residual = readout - &map.dot(&chart);
            let band = entrywise_band_norm(
                map.mapv(f64::abs)
                    .dot(&absolute_chart)
                    .mapv(|magnitude| accumulation_band(rank + 1, magnitude))
                    + &readout.mapv(|entry| accumulation_growth(1) * entry.abs()),
            );
            readout_bounds.push(spectral_norm_bounds(
                &residual,
                band,
                "linear quotient: readout",
            )?);
            readout_maps.push(map);
        }

        let mut descended = Vec::with_capacity(transitions.len());
        let mut quotient_bounds = Vec::with_capacity(transitions.len());
        let mut realization_bounds = Vec::with_capacity(transitions.len());
        for transition in transitions {
            let absolute_transition = transition.mapv(f64::abs);
            let moved = chart.dot(transition);
            let map = moved.dot(&section);
            let absolute_map = map.mapv(f64::abs);
            let quotient_residual = &moved - &map.dot(&chart);
            let quotient_band = entrywise_band_norm(
                absolute_chart
                    .dot(&absolute_transition)
                    .mapv(|magnitude| accumulation_band(dimension + 1, magnitude))
                    + &absolute_map
                        .dot(&absolute_chart)
                        .mapv(|magnitude| accumulation_band(rank + 1, magnitude)),
            );
            quotient_bounds.push(spectral_norm_bounds(
                &quotient_residual,
                quotient_band,
                "linear quotient: quotient contract",
            )?);
            let realization_residual = &transition.dot(&section) - &section.dot(&map);
            let realization_band = entrywise_band_norm(
                absolute_transition
                    .dot(&absolute_section)
                    .mapv(|magnitude| accumulation_band(dimension + 1, magnitude))
                    + &absolute_section
                        .dot(&absolute_map)
                        .mapv(|magnitude| accumulation_band(rank + 1, magnitude)),
            );
            realization_bounds.push(spectral_norm_bounds(
                &realization_residual,
                realization_band,
                "linear quotient: realization contract",
            )?);
            descended.push(map);
        }
        Ok(Self {
            chart,
            readout_maps,
            descended,
            readout_bounds,
            quotient_bounds,
            realization_bounds,
            section_bounds,
        })
    }
}

/// The resolved row space of a matrix: its singular values, the band, the rank
/// and the leading right singular vectors as rows.
struct ResolvedRowSpace {
    singular_values: Vec<f64>,
    band: f64,
    rank: usize,
    rows: Array2<f64>,
}

fn resolved_row_space(
    matrix: &Array2<f64>,
    formation: f64,
    context: &'static str,
) -> Result<ResolvedRowSpace, StateError> {
    let (rows, cols) = matrix.dim();
    let (_, sigma, vt) = matrix
        .svd(false, true)
        .map_err(|source| StateError::Svd { context, source })?;
    let vt = vt.ok_or(StateError::Svd {
        context,
        source: FaerLinalgError::SvdNoConvergence { context },
    })?;
    let mut order: Vec<usize> = (0..sigma.len()).collect();
    order.sort_by(|&left, &right| sigma[right].total_cmp(&sigma[left]));
    let singular_values: Vec<f64> = order.iter().map(|&index| sigma[index]).collect();
    let sigma_max = singular_values.first().copied().unwrap_or(0.0);
    let band = factor_singular_band(rows, cols, sigma_max) + formation;
    let rank = singular_values.iter().filter(|&&value| value > band).count();
    let mut resolved = Array2::<f64>::zeros((rank, cols));
    for (row, &index) in order.iter().take(rank).enumerate() {
        resolved.row_mut(row).assign(&vt.row(index));
    }
    Ok(ResolvedRowSpace {
        singular_values,
        band,
        rank,
        rows: resolved,
    })
}

fn spectral_norm_bounds(
    matrix: &Array2<f64>,
    formation: f64,
    context: &'static str,
) -> Result<SpectralNormBounds, StateError> {
    if matrix.is_empty() {
        return Ok(SpectralNormBounds {
            lower: 0.0,
            upper: formation,
        });
    }
    let (rows, cols) = matrix.dim();
    let (_, sigma, _) = matrix
        .svd(false, false)
        .map_err(|source| StateError::Svd { context, source })?;
    let sigma_max = sigma.iter().fold(0.0_f64, |largest, &value| largest.max(value));
    let band = factor_singular_band(rows, cols, sigma_max) + formation;
    Ok(SpectralNormBounds {
        lower: (sigma_max - band).max(0.0),
        upper: sigma_max + band,
    })
}

/// `‖B‖_F` of an entrywise error bound `B`, which bounds the spectral norm of the
/// error.
fn entrywise_band_norm(band: Array2<f64>) -> f64 {
    band.iter().map(|entry| entry * entry).sum::<f64>().sqrt()
}

fn linear_family_dimension(
    readouts: &[ArrayView2<'_, f64>],
    transitions: &[ArrayView2<'_, f64>],
) -> Result<usize, StateError> {
    let dimension = readouts
        .first()
        .ok_or(StateError::EmptyFamily {
            context: "linear quotient: readouts",
        })?
        .ncols();
    for readout in readouts {
        require_sample(readout.view(), dimension, "linear quotient: readout")?;
    }
    for transition in transitions {
        require_dimension(transition.nrows(), dimension, "linear quotient: transition rows")?;
        require_sample(transition.view(), dimension, "linear quotient: transition")?;
    }
    Ok(dimension)
}

/// Errors and refusals of the sufficient-state checks.
#[derive(Debug)]
pub enum StateError {
    /// No futures, responses, states or codes were stated.
    EmptyFamily { context: &'static str },
    /// Two dimensions that must agree do not.
    DimensionMismatch {
        context: &'static str,
        expected: usize,
        found: usize,
    },
    /// A stated sample, value, Jacobian or roundoff bound is not finite.
    NonFinite { context: &'static str },
    /// A bound that must be non-negative is negative.
    NegativeBound { context: &'static str, value: f64 },
    /// The declared fidelity tolerance is negative or not finite.
    InvalidFidelity { value: f64 },
    /// A native map could not execute.
    Execution { reason: String },
    /// `E(D(E h))` differs from `E(h)` by more than the arithmetic explains, so
    /// the decoder is not a section of the encoder at this state's code.
    NotASection {
        state: usize,
        code_defect: f64,
        roundoff: f64,
    },
    /// Every stated state lies on the chart's section within the decoder's
    /// roundoff, so each comparison was of a state with itself and no fibre was
    /// tested.
    VacuousFiberTest { states: usize },
    /// A singular value decomposition failed.
    Svd {
        context: &'static str,
        source: FaerLinalgError,
    },
    /// An evaluated defect could not be expressed as an evidence status.
    Evidence { source: EvidenceStatusError },
}

impl fmt::Display for StateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyFamily { context } => write!(formatter, "{context}: nothing was stated"),
            Self::DimensionMismatch {
                context,
                expected,
                found,
            } => write!(formatter, "{context}: expected dimension {expected}, found {found}"),
            Self::NonFinite { context } => write!(formatter, "{context}: non-finite value"),
            Self::NegativeBound { context, value } => {
                write!(formatter, "{context}: bound {value} is negative")
            }
            Self::InvalidFidelity { value } => write!(
                formatter,
                "declared fidelity tolerance {value} is not a finite non-negative number"
            ),
            Self::Execution { reason } => write!(formatter, "native map failed: {reason}"),
            Self::NotASection {
                state,
                code_defect,
                roundoff,
            } => write!(
                formatter,
                "fiber test: at state {state} the decoder is not a section: E(D(E h)) differs \
                 from E(h) by {code_defect:e}, above the roundoff bound {roundoff:e}"
            ),
            Self::VacuousFiberTest { states } => write!(
                formatter,
                "fiber test: all {states} states lie on the chart's section, so no fibre was tested"
            ),
            Self::Svd { context, source } => {
                write!(formatter, "{context}: singular value decomposition failed: {source}")
            }
            Self::Evidence { source } => {
                write!(formatter, "evidence status refused an evaluated defect: {source}")
            }
        }
    }
}

impl std::error::Error for StateError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Svd { source, .. } => Some(source),
            Self::Evidence { source } => Some(source),
            _ => None,
        }
    }
}

/// The stated item whose certified defect is largest, the uniform bound over all
/// stated items, the largest combined roundoff, and the number of items.
struct DefectRecord {
    violation: Option<(usize, f64, f64, EvidenceStatus<(), ()>)>,
    bound: f64,
    roundoff: f64,
    count: usize,
}

impl DefectRecord {
    fn new() -> Self {
        Self {
            violation: None,
            bound: 0.0,
            roundoff: 0.0,
            count: 0,
        }
    }

    fn observe(&mut self, index: usize, defect: f64, roundoff: f64) -> Result<(), StateError> {
        let item = evaluated_defect(defect, roundoff)?;
        self.count += 1;
        self.bound = self.bound.max(certified_upper(&item));
        self.roundoff = self.roundoff.max(roundoff);
        if item.refutes_at_most(0.0) {
            let larger = match &self.violation {
                Some((_, _, _, worst)) => certified_lower(&item) > certified_lower(worst),
                None => true,
            };
            if larger {
                self.violation = Some((index, defect, roundoff, item));
            }
        }
        Ok(())
    }
}

/// One evaluated defect with its combined roundoff, as the status supports.rs
/// owns: exact up to numerical error over the single evaluated item. Verdicts
/// read its rounded bounds and threshold predicates, the derivation
/// [`EvidenceStatus::counterexample`] reads, so no copy of that arithmetic lives
/// here.
fn evaluated_defect(value: f64, roundoff: f64) -> Result<EvidenceStatus<(), ()>, StateError> {
    EvidenceStatus::exact(
        value,
        roundoff,
        ExactBasis::Exhaustive { cardinality: 1 },
        None,
        (),
    )
    .map_err(|source| StateError::Evidence { source })
}

/// The item's certified lower bound. An exact status always has one.
fn certified_lower(item: &EvidenceStatus<(), ()>) -> f64 {
    item.lower_bound().unwrap_or(f64::NEG_INFINITY)
}

/// The item's certified upper bound. An exact status always has one.
fn certified_upper(item: &EvidenceStatus<(), ()>) -> f64 {
    item.upper_bound().unwrap_or(f64::INFINITY)
}

fn evaluated<M: NativeMap + ?Sized>(
    map: &M,
    input: ArrayView1<'_, f64>,
    input_roundoff: f64,
    context: &'static str,
) -> Result<Evaluation, StateError> {
    require_dimension(input.len(), map.input_dimension(), context)?;
    let evaluation = map.evaluate(input, input_roundoff)?;
    require_dimension(evaluation.value.len(), map.output_dimension(), context)?;
    if !evaluation.roundoff.is_finite()
        || evaluation.roundoff < 0.0
        || evaluation.value.iter().any(|value| !value.is_finite())
    {
        return Err(StateError::NonFinite { context });
    }
    Ok(evaluation)
}

fn require_dimension(found: usize, expected: usize, context: &'static str) -> Result<(), StateError> {
    if found == expected {
        Ok(())
    } else {
        Err(StateError::DimensionMismatch {
            context,
            expected,
            found,
        })
    }
}

fn require_sample(
    sample: ArrayView2<'_, f64>,
    dimension: usize,
    context: &'static str,
) -> Result<(), StateError> {
    if sample.nrows() == 0 {
        return Err(StateError::EmptyFamily { context });
    }
    require_dimension(sample.ncols(), dimension, context)?;
    if sample.iter().any(|value| !value.is_finite()) {
        return Err(StateError::NonFinite { context });
    }
    Ok(())
}

fn sup_distance(left: ArrayView1<'_, f64>, right: ArrayView1<'_, f64>) -> f64 {
    left.iter()
        .zip(right.iter())
        .fold(0.0_f64, |largest, (a, b)| largest.max((a - b).abs()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::{array, s};

    /// A fixture map given by closed forms. `evaluate` returns the value and its
    /// roundoff bound for an input roundoff; `jacobian` returns the Jacobian and
    /// its formation bound.
    struct Closed {
        input: usize,
        output: usize,
        evaluate: for<'v> fn(ArrayView1<'v, f64>, f64) -> (Array1<f64>, f64),
        jacobian: for<'v> fn(ArrayView1<'v, f64>) -> (Array2<f64>, f64),
    }

    impl NativeMap for Closed {
        fn input_dimension(&self) -> usize {
            self.input
        }

        fn output_dimension(&self) -> usize {
            self.output
        }

        fn evaluate(
            &self,
            input: ArrayView1<'_, f64>,
            input_roundoff: f64,
        ) -> Result<Evaluation, StateError> {
            let (value, roundoff) = (self.evaluate)(input, input_roundoff);
            Ok(Evaluation { value, roundoff })
        }
    }

    impl DifferentiableNativeMap for Closed {
        fn jacobian(&self, input: ArrayView1<'_, f64>) -> Result<JacobianEvaluation, StateError> {
            let (matrix, roundoff) = (self.jacobian)(input);
            Ok(JacobianEvaluation { matrix, roundoff })
        }
    }

    /// A fixture affine map `x ↦ Mx + c`. Row `i` is an inner product of length
    /// `n` plus one addition, so it rounds within `γ_{n+1}(Σⱼ|Mᵢⱼxⱼ| + |cᵢ|)`.
    /// Moving the input by `δ` moves the value by at most `‖M‖∞·δ`. The Jacobian
    /// `M` is exact.
    struct Affine {
        matrix: Array2<f64>,
        offset: Array1<f64>,
    }

    impl NativeMap for Affine {
        fn input_dimension(&self) -> usize {
            self.matrix.ncols()
        }

        fn output_dimension(&self) -> usize {
            self.matrix.nrows()
        }

        fn evaluate(
            &self,
            input: ArrayView1<'_, f64>,
            input_roundoff: f64,
        ) -> Result<Evaluation, StateError> {
            let value = self.matrix.dot(&input) + &self.offset;
            let mut roundoff = 0.0_f64;
            let mut row_sum_norm = 0.0_f64;
            for (row, shift) in self.matrix.rows().into_iter().zip(self.offset.iter()) {
                let absolute_sum = row
                    .iter()
                    .zip(input.iter())
                    .map(|(entry, coordinate)| (entry * coordinate).abs())
                    .sum::<f64>()
                    + shift.abs();
                roundoff = roundoff.max(accumulation_band(row.len() + 1, absolute_sum));
                row_sum_norm = row_sum_norm.max(row.iter().map(|entry| entry.abs()).sum::<f64>());
            }
            Ok(Evaluation {
                value,
                roundoff: roundoff + row_sum_norm * input_roundoff,
            })
        }
    }

    impl DifferentiableNativeMap for Affine {
        fn jacobian(&self, input: ArrayView1<'_, f64>) -> Result<JacobianEvaluation, StateError> {
            require_dimension(input.len(), self.matrix.ncols(), "affine fixture: Jacobian")?;
            Ok(JacobianEvaluation {
                matrix: self.matrix.clone(),
                roundoff: 0.0,
            })
        }
    }

    /// `o(h) = h²` on `ℝ¹`: the current observation. One product rounds once;
    /// moving the input by `δ` moves the value by at most `(2|h| + δ)δ`.
    fn square() -> Closed {
        Closed {
            input: 1,
            output: 1,
            evaluate: |h, delta| {
                let x = h[0];
                (
                    array![x * x],
                    accumulation_growth(1) * x * x + (2.0 * x.abs() + delta) * delta,
                )
            },
            jacobian: |h| (array![[2.0 * h[0]]], 0.0),
        }
    }

    /// `o(T h) = (h + 1)²`: shift, then observe. The sum and the product give
    /// `γ₃(|h| + 1)²`.
    fn shifted_square() -> Closed {
        Closed {
            input: 1,
            output: 1,
            evaluate: |h, delta| {
                let x = h[0];
                let magnitude = x.abs() + 1.0;
                (
                    array![(x + 1.0) * (x + 1.0)],
                    accumulation_growth(3) * magnitude * magnitude
                        + (2.0 * magnitude + delta) * delta,
                )
            },
            jacobian: |h| {
                (
                    array![[2.0 * (h[0] + 1.0)]],
                    accumulation_growth(1) * 2.0 * (h[0].abs() + 1.0),
                )
            },
        }
    }

    /// The section `D(z) = √z` of the current observation. `√` is correctly
    /// rounded and ½-Hölder: `|√x − √z| ≤ √|x − z|`.
    fn square_root() -> Closed {
        Closed {
            input: 1,
            output: 1,
            evaluate: |z, delta| {
                let root = z[0].sqrt();
                (array![root], accumulation_growth(1) * root + delta.sqrt())
            },
            jacobian: |z| {
                let root = z[0].sqrt();
                (array![[0.5 / root]], accumulation_growth(2) * 0.5 / root)
            },
        }
    }

    /// `D(z) = 2√z`, which is not a section of `h²`.
    fn doubled_square_root() -> Closed {
        Closed {
            input: 1,
            output: 1,
            evaluate: |z, delta| {
                let root = z[0].sqrt();
                (
                    array![2.0 * root],
                    accumulation_growth(1) * 2.0 * root + 2.0 * delta.sqrt(),
                )
            },
            jacobian: |z| {
                let root = z[0].sqrt();
                (array![[1.0 / root]], accumulation_growth(2) / root)
            },
        }
    }

    /// `(a, b) ↦ a²` on `ℝ²`.
    fn first_square() -> Closed {
        Closed {
            input: 2,
            output: 1,
            evaluate: |h, delta| {
                let x = h[0];
                (
                    array![x * x],
                    accumulation_growth(1) * x * x + (2.0 * x.abs() + delta) * delta,
                )
            },
            jacobian: |h| (array![[2.0 * h[0], 0.0]], 0.0),
        }
    }

    /// `(a, b) ↦ (a + 1)²` on `ℝ²`.
    fn first_shifted_square() -> Closed {
        Closed {
            input: 2,
            output: 1,
            evaluate: |h, delta| {
                let x = h[0];
                let magnitude = x.abs() + 1.0;
                (
                    array![(x + 1.0) * (x + 1.0)],
                    accumulation_growth(3) * magnitude * magnitude
                        + (2.0 * magnitude + delta) * delta,
                )
            },
            jacobian: |h| {
                (
                    array![[2.0 * (h[0] + 1.0), 0.0]],
                    accumulation_growth(1) * 2.0 * (h[0].abs() + 1.0),
                )
            },
        }
    }

    /// `(z, n) ↦ z`: observe the first coordinate.
    fn first_coordinate() -> Affine {
        Affine {
            matrix: array![[1.0, 0.0]],
            offset: array![0.0],
        }
    }

    /// `(a, b) ↦ a + b`, the observation after `T(a, b) = (a + b, b)`.
    fn coordinate_sum() -> Affine {
        Affine {
            matrix: array![[1.0, 1.0]],
            offset: array![0.0],
        }
    }

    /// The section `z ↦ (z, 0)` of the first coordinate.
    fn zero_section() -> Affine {
        Affine {
            matrix: array![[1.0], [0.0]],
            offset: array![0.0, 0.0],
        }
    }

    /// The section `z ↦ (z, 3z)` of the first coordinate.
    fn tilted_section() -> Affine {
        Affine {
            matrix: array![[1.0], [3.0]],
            offset: array![0.0, 0.0],
        }
    }

    /// The identity on a one-dimensional code.
    fn code_identity() -> Affine {
        Affine {
            matrix: array![[1.0]],
            offset: array![0.0],
        }
    }

    /// `T(z, n) = (z, n + 1)`: the unobserved coordinate counts steps.
    fn counting_transition() -> Affine {
        Affine {
            matrix: array![[1.0, 0.0], [0.0, 1.0]],
            offset: array![0.0, 1.0],
        }
    }

    /// `T(z, n) = (z + n, n)`: the observed coordinate drifts by the unobserved
    /// one, and the section `n = 0` is fixed.
    fn drifting_transition() -> Affine {
        Affine {
            matrix: array![[1.0, 1.0], [0.0, 1.0]],
            offset: array![0.0, 0.0],
        }
    }

    /// A9, the h² fixture. The current observation `o(h) = h²` merges `±1`, and
    /// the future `h ↦ h + 1` separates them (`0` against `4`), so the fiber test
    /// refuses the current-observation chart. Two controls: the observation alone
    /// agrees at the merged pair, and the chart's full rank at `h = ±1` does not
    /// detect the merge.
    #[test]
    fn h_squared_fixture_refuses_the_current_observation_chart() {
        let observe = square();
        let observe_after_shift = shifted_square();
        let section = square_root();
        let chart = StateChart {
            encoder: &observe,
            decoder: &section,
        };
        let states = array![[-1.0], [1.0], [-0.5]];

        let futures: [&dyn NativeMap; 2] = [&observe, &observe_after_shift];
        let refusal = fiber_test(&chart, &futures, states.view(), 0.0).expect("fiber test");
        match &refusal {
            FiberVerdict::Separated {
                witness,
                distance,
                roundoff,
                fidelity,
            } => {
                assert_eq!(
                    (witness.state, witness.future),
                    (0, 1),
                    "h = -1 against h = +1 under o∘T"
                );
                assert_eq!(witness.representative, array![1.0]);
                assert_eq!(*distance, 4.0, "(-1 + 1)² = 0 against (1 + 1)² = 4");
                // The two shifted-square bounds γ₃·2².
                assert!(*roundoff <= 8.0 * accumulation_growth(3), "found {roundoff}");
                assert_eq!(*fidelity, 0.0);
                // E(-1) rounds within γ₁, D(1) within γ₁, and E at D(1) within
                // γ₁ + (2 + γ₁)γ₁.
                assert!(
                    witness.merge_bound <= 5.0 * accumulation_growth(1),
                    "the chart merges -1 and +1 to roundoff, found {}",
                    witness.merge_bound
                );
            }
            other => panic!("the current-observation chart must be refused, got {other:?}"),
        }
        let evidence = refusal
            .evidence()
            .expect("a certified separation is a counterexample");
        assert!(matches!(evidence, EvidenceStatus::Counterexample { .. }));
        assert!(evidence.refutes_at_most(0.0));

        let observation_only: [&dyn NativeMap; 1] = [&observe];
        match fiber_test(&chart, &observation_only, states.view(), 0.0).expect("fiber test") {
            FiberVerdict::Unresolved {
                tested_states,
                vacuous_states,
                futures,
                separation_lower_bound,
                separation_upper_bound,
                ..
            } => {
                assert_eq!((tested_states, vacuous_states, futures), (2, 1, 1));
                assert_eq!(separation_lower_bound, 0.0);
                // Two bounds of γ₁ at h = ±1, rounded up once.
                assert!(
                    separation_upper_bound <= (2.0 * accumulation_growth(1)).next_up(),
                    "the current observation agrees at the merged pair, found {separation_upper_bound}"
                );
            }
            other => panic!("the observation alone separates nothing, got {other:?}"),
        }

        let differentiable: [&dyn DifferentiableNativeMap; 1] = [&observe];
        let ranks = constant_rank_check(&differentiable, array![[-1.0], [1.0]].view())
            .expect("rank check");
        assert_eq!(ranks.local_dimension(0), Some(LocalDimension::Certified(1)));
        assert_eq!(ranks.local_dimension(1), Some(LocalDimension::Certified(1)));
    }

    /// A check on decoder sections does not test fibres. States on the section
    /// `h = √(h²)` compare each state with itself, and the test refuses rather
    /// than report agreement. A decoder that is not a section is refused, and so
    /// is an invalid declared fidelity.
    #[test]
    fn fiber_test_refuses_section_only_samples_and_non_sections() {
        let observe = square();
        let observe_after_shift = shifted_square();
        let section = square_root();
        let chart = StateChart {
            encoder: &observe,
            decoder: &section,
        };
        let futures: [&dyn NativeMap; 2] = [&observe, &observe_after_shift];

        let on_section = array![[0.5], [1.0], [2.0]];
        match fiber_test(&chart, &futures, on_section.view(), 0.0) {
            Err(StateError::VacuousFiberTest { states }) => assert_eq!(states, 3),
            other => panic!("a section-only sample must be refused, got {other:?}"),
        }

        let not_a_section = doubled_square_root();
        let broken = StateChart {
            encoder: &observe,
            decoder: &not_a_section,
        };
        match fiber_test(&broken, &futures, array![[-1.0]].view(), 0.0) {
            Err(StateError::NotASection {
                state, code_defect, ..
            }) => {
                assert_eq!(state, 0);
                assert_eq!(code_defect, 3.0, "E(D(E(-1))) = 4 against E(-1) = 1");
            }
            other => panic!("a non-section decoder must be refused, got {other:?}"),
        }

        match fiber_test(&chart, &futures, array![[-1.0]].view(), -1.0) {
            Err(StateError::InvalidFidelity { value }) => assert_eq!(value, -1.0),
            other => panic!("a negative declared fidelity must be refused, got {other:?}"),
        }
    }

    /// A sufficient chart with non-trivial fibres. The futures read only `a` of
    /// `(a, b)`, so the chart `(a, b) ↦ a` with section `a ↦ (a, 0)` passes at
    /// states off the section, within a fidelity declared at twice the futures'
    /// combined roundoff. Control: a declared fidelity of zero cannot be certified
    /// from floating point, so it stays unresolved.
    #[test]
    fn a_sufficient_chart_passes_off_the_section_within_its_roundoff() {
        let observe = first_square();
        let observe_after_shift = first_shifted_square();
        let encoder = first_coordinate();
        let section = zero_section();
        let chart = StateChart {
            encoder: &encoder,
            decoder: &section,
        };
        let futures: [&dyn NativeMap; 2] = [&observe, &observe_after_shift];
        let states = array![[-1.0, 5.0], [2.0, -3.0]];

        // The largest pair of shifted-square bounds is at |a| = 2: 2·γ₃·3².
        let fidelity = 2.0 * 18.0 * accumulation_growth(3);
        match fiber_test(&chart, &futures, states.view(), fidelity).expect("fiber test") {
            verdict @ FiberVerdict::WithinFidelity {
                tested_states,
                vacuous_states,
                separation_upper_bound,
                ..
            } => {
                assert_eq!((tested_states, vacuous_states), (2, 0));
                assert!(separation_upper_bound <= fidelity);
                let evidence = verdict.evidence().expect("a bound is a uniform bound");
                assert!(evidence.certifies_at_most(fidelity));
            }
            other => panic!("the first-coordinate chart is sufficient, got {other:?}"),
        }

        match fiber_test(&chart, &futures, states.view(), 0.0).expect("fiber test") {
            FiberVerdict::Unresolved {
                separation_lower_bound,
                separation_upper_bound,
                ..
            } => {
                assert_eq!(separation_lower_bound, 0.0);
                assert!(separation_upper_bound > 0.0);
            }
            other => panic!("exact agreement is never certified, got {other:?}"),
        }
    }

    /// A9, the quotient-versus-realization counterexample `T(z, n) = (z, n + 1)`
    /// with only `z` observed. The quotient contract holds at every stated state.
    /// The stationary realization `D' = D`, the one an autonomous program needs,
    /// fails at every code, for the section `(z, 0)` and for the section `(z, 3z)`.
    /// Control: the per-step decoder `D'(z) = (z, 1)` after `D(z) = (z, 0)` does
    /// realize one step, so the refutation is of the stationary form only.
    #[test]
    fn counting_transition_satisfies_the_quotient_but_not_the_realization_contract() {
        let transition = counting_transition();
        let observe = first_coordinate();
        let identity = code_identity();
        let quotient = QuotientContract {
            transition: &transition,
            encoder: &observe,
            next_encoder: &observe,
            descended: &identity,
        };
        let states = array![[0.0, 0.0], [1.5, -2.0], [-3.0, 7.0]];
        match quotient.check(states.view()).expect("quotient check") {
            QuotientContractVerdict::Bounded { bound, .. } => {
                // At (-3, 7): T rounds within 8γ₃, E'(T h) within 3γ₃ + 8γ₃,
                // E(h) within 3γ₃ and g(E h) within 3γ₂ + 3γ₃: 14γ₃ + 3γ₂ ≤ 17γ₃.
                assert!(
                    bound <= 17.0 * accumulation_growth(3),
                    "the code descends to roundoff, found {bound}"
                );
            }
            other => panic!("the quotient contract holds, got {other:?}"),
        }

        let codes = array![[0.0], [1.5], [-3.0]];
        let zero = zero_section();
        let tilted = tilted_section();
        let sections: [&dyn NativeMap; 2] = [&zero, &tilted];
        for section in sections {
            let realization = RealizationContract {
                transition: &transition,
                decoder: section,
                next_decoder: section,
                descended: &identity,
            };
            match realization.check(codes.view()).expect("realization check") {
                RealizationContractVerdict::Violated { code, defect, .. } => {
                    assert_eq!(code, 0);
                    assert_eq!(defect, 1.0, "T(D z) sits one step along the fibre from D(z)");
                }
                other => panic!("no section realizes the counting transition, got {other:?}"),
            }
        }

        let unit_section = Affine {
            matrix: array![[1.0], [0.0]],
            offset: array![0.0, 1.0],
        };
        let per_step = RealizationContract {
            transition: &transition,
            decoder: &zero,
            next_decoder: &unit_section,
            descended: &identity,
        };
        match per_step.check(codes.view()).expect("realization check") {
            RealizationContractVerdict::Bounded { bound, .. } => {
                // At z = -3: T(D z) rounds within 3γ₃ + 3γ₂ and D'(g z) within
                // 3γ₂ + 3γ₂: 3γ₃ + 9γ₂ ≤ 12γ₃.
                assert!(
                    bound <= 12.0 * accumulation_growth(3),
                    "a per-step decoder realizes one step, found {bound}"
                );
            }
            other => panic!("the per-step decoder realizes one step, got {other:?}"),
        }
    }

    /// The converse: `T(z, n) = (z + n, n)` fixes the section `(z, 0)`, so the
    /// realization contract holds, while the quotient contract fails at states
    /// with `n ≠ 0`, most at `n = 7`.
    #[test]
    fn drifting_transition_satisfies_the_realization_but_not_the_quotient_contract() {
        let transition = drifting_transition();
        let observe = first_coordinate();
        let identity = code_identity();
        let section = zero_section();
        let realization = RealizationContract {
            transition: &transition,
            decoder: &section,
            next_decoder: &section,
            descended: &identity,
        };
        match realization
            .check(array![[0.0], [1.5], [-3.0]].view())
            .expect("realization check")
        {
            RealizationContractVerdict::Bounded { bound, .. } => {
                // At z = -3: D(z) rounds within 3γ₂, T(D z) within 3γ₃ + 2·3γ₂,
                // g(z) within 3γ₂ and D'(g z) within 3γ₂ + 3γ₂: 3γ₃ + 12γ₂ ≤ 15γ₃.
                assert!(
                    bound <= 15.0 * accumulation_growth(3),
                    "the section is fixed to roundoff, found {bound}"
                );
            }
            other => panic!("the section realizes the drift, got {other:?}"),
        }

        let quotient = QuotientContract {
            transition: &transition,
            encoder: &observe,
            next_encoder: &observe,
            descended: &identity,
        };
        match quotient
            .check(array![[0.0, 0.0], [1.5, -2.0], [-3.0, 7.0]].view())
            .expect("quotient check")
        {
            QuotientContractVerdict::Violated { state, defect, .. } => {
                assert_eq!(state, 2);
                assert_eq!(defect, 7.0);
            }
            other => panic!("the observed coordinate does not descend, got {other:?}"),
        }
        let refuted = quotient
            .check(array![[0.0, 0.0], [1.5, -2.0], [-3.0, 7.0]].view())
            .expect("quotient check")
            .evidence()
            .expect("a certified violation is a counterexample");
        assert!(matches!(
            refuted,
            EvidenceStatus::Counterexample {
                witness: StateRow(2),
                ..
            }
        ));
        assert!(refuted.refutes_at_most(0.0));
    }

    /// The singular-point caveat and the generation assumption. The current
    /// observation `h²` loses rank at `h = 0`, while the generating family
    /// `{h², (h + 1)²}` has constant rank 1 there. Observing `a` of `(a, b)` has
    /// rank 1, and adding the observation after `T(a, b) = (a + b, b)` gives 2: a
    /// family that does not generate understates the minimal dimension.
    #[test]
    fn rank_drops_at_singular_points_and_depends_on_generation() {
        let observe = square();
        let observe_after_shift = shifted_square();
        let states = array![[-1.0], [0.0], [1.0]];

        let current: [&dyn DifferentiableNativeMap; 1] = [&observe];
        let ranks = constant_rank_check(&current, states.view()).expect("rank check");
        assert_eq!(ranks.generic_rank, 1);
        assert_eq!(ranks.local_dimension(0), Some(LocalDimension::Certified(1)));
        assert_eq!(
            ranks.local_dimension(1),
            Some(LocalDimension::BelowGeneric {
                resolved_rank: 0,
                generic_rank: 1,
                largest_unresolved_singular_value: 0.0,
                band: 0.0,
            })
        );
        assert_eq!(ranks.local_dimension(2), Some(LocalDimension::Certified(1)));
        assert_eq!(ranks.local_dimension(3), None);
        assert!(matches!(
            ranks.rank_evidence(0),
            Some(Ok(EvidenceStatus::Exact {
                value,
                basis: ExactBasis::Algebraic,
                ..
            })) if value == 1.0
        ));
        assert!(matches!(
            ranks.rank_evidence(1),
            Some(Ok(EvidenceStatus::Unresolved { lower, upper, .. })) if lower == 0.0 && upper == 1.0
        ));

        let generating: [&dyn DifferentiableNativeMap; 2] = [&observe, &observe_after_shift];
        let generated = constant_rank_check(&generating, states.view()).expect("rank check");
        for state in 0..3 {
            assert_eq!(
                generated.local_dimension(state),
                Some(LocalDimension::Certified(1)),
                "state {state}"
            );
        }

        let first = first_coordinate();
        let after_transition = coordinate_sum();
        let pair_states = array![[0.5, -1.0], [2.0, 3.0]];
        let observed_only: [&dyn DifferentiableNativeMap; 1] = [&first];
        let partial = constant_rank_check(&observed_only, pair_states.view()).expect("rank check");
        assert_eq!(partial.generic_rank, 1);
        assert_eq!(partial.states[0].observed_directions.dim(), (1, 2));
        let closed: [&dyn DifferentiableNativeMap; 2] = [&first, &after_transition];
        let full = constant_rank_check(&closed, pair_states.view()).expect("rank check");
        assert_eq!(full.generic_rank, 2);
        assert_eq!(full.local_dimension(0), Some(LocalDimension::Certified(2)));

        // BelowGeneric names what the band left unresolved; it does not certify a
        // rank drop. `f(h) = h²/2` has exact rank 1 at `h = ε`, but its slope `ε`
        // sits below the declared formation bound `2ε`.
        let faint = Closed {
            input: 1,
            output: 1,
            evaluate: |h, delta| {
                let x = h[0];
                (
                    array![0.5 * x * x],
                    accumulation_growth(1) * 0.5 * x * x + (x.abs() + 0.5 * delta) * delta,
                )
            },
            jacobian: |h| (array![[h[0]]], 2.0 * f64::EPSILON),
        };
        let faint_family: [&dyn DifferentiableNativeMap; 1] = [&faint];
        let faint_ranks =
            constant_rank_check(&faint_family, array![[1.0], [f64::EPSILON]].view())
                .expect("rank check");
        match faint_ranks.local_dimension(1) {
            Some(LocalDimension::BelowGeneric {
                resolved_rank,
                generic_rank,
                largest_unresolved_singular_value,
                band,
            }) => {
                assert_eq!((resolved_rank, generic_rank), (0, 1));
                assert!(
                    largest_unresolved_singular_value > 0.0
                        && largest_unresolved_singular_value <= band,
                    "the nonzero slope must sit inside the band, found \
                     {largest_unresolved_singular_value:e} against {band:e}"
                );
            }
            other => panic!("an unresolved nonzero slope is BelowGeneric, got {other:?}"),
        }
    }

    /// `½·H₄`, the 4×4 Hadamard matrix scaled to be orthogonal and symmetric.
    /// Every entry is dyadic, so products with dyadic blocks are exact in f64.
    fn dyadic_frame() -> Array2<f64> {
        array![
            [0.5, 0.5, 0.5, 0.5],
            [0.5, -0.5, 0.5, -0.5],
            [0.5, 0.5, -0.5, -0.5],
            [0.5, -0.5, -0.5, 0.5]
        ]
    }

    /// `T = H T_u H` with `T_u = [[A11, 0], [c·A21, A22]]`. Rows in the span of the
    /// first two frame rows stay there, so the observable subspace of the readout
    /// `e₀ᵀ H` is those two rows, and `c` couples the unobserved block to them.
    fn planted_transition(coupling: f64) -> Array2<f64> {
        let frame = dyadic_frame();
        let block = array![
            [0.5, 1.0, 0.0, 0.0],
            [-1.0, 0.25, 0.0, 0.0],
            [0.375 * coupling, 0.0, 0.875, 0.25],
            [0.0, -0.75 * coupling, 0.125, 0.75]
        ];
        frame.dot(&block).dot(&frame)
    }

    /// The planted observable chart descends exactly: every product is dyadic, so
    /// the readout, quotient and section residuals are computed as exact zeros.
    /// Its realization leaks the coupling: `T Qᵀ − Qᵀ G = H [0; A21]`, whose
    /// spectral norm is `‖A21‖₂ = 0.75`. Controls: the readout row alone leaks
    /// `[0, 1, 0, 0] H` of norm 1, and removing the coupling realizes the chart.
    #[test]
    fn declared_observable_chart_descends_exactly_and_its_realization_leaks_the_coupling() {
        let frame = dyadic_frame();
        let readout = frame.slice(s![..1, ..]).to_owned();
        let transition = planted_transition(1.0);
        let planted = frame.slice(s![..2, ..]).to_owned();
        let measured =
            LinearStateQuotient::measure(planted, &[readout.view()], &[transition.view()])
                .expect("measure");
        assert_eq!(measured.readout_bounds[0].lower, 0.0);
        assert_eq!(measured.quotient_bounds[0].lower, 0.0);
        assert_eq!(measured.section_bounds.lower, 0.0);
        assert_eq!(measured.descended[0], array![[0.5, 1.0], [-1.0, 0.25]]);
        let realization = measured.realization_bounds[0];
        assert!(
            realization.lower > 0.0 && realization.lower <= 0.75 && 0.75 <= realization.upper,
            "the realization defect 0.75 must lie in {realization:?}"
        );
        let leaks = realization.evidence(4).expect("both sides are derived");
        assert!(leaks.refutes_at_most(0.0));
        assert!(leaks.certifies_at_most(realization.upper));

        let unclosed = LinearStateQuotient::measure(
            frame.slice(s![..1, ..]).to_owned(),
            &[readout.view()],
            &[transition.view()],
        )
        .expect("measure");
        let leak = unclosed.quotient_bounds[0];
        assert!(
            leak.lower > 0.0 && leak.lower <= 1.0 && 1.0 <= leak.upper,
            "the unclosed chart's leakage 1 must lie in {leak:?}"
        );

        let decoupled = planted_transition(0.0);
        let realized = LinearStateQuotient::measure(
            frame.slice(s![..2, ..]).to_owned(),
            &[readout.view()],
            &[decoupled.view()],
        )
        .expect("measure");
        assert_eq!(realized.realization_bounds[0].lower, 0.0);
    }

    /// The closure recovers the planted two-dimensional observable subspace from
    /// the readout alone. Its chart comes from singular vectors, so its residuals
    /// are roundoff rather than exact zeros: the test asserts they are resolved
    /// below the unclosed chart's certified leakage, with no tolerance of its own.
    /// With no transitions the chart is the readout span.
    #[test]
    fn closure_recovers_the_planted_observable_subspace() {
        let frame = dyadic_frame();
        let readout = frame.slice(s![..1, ..]).to_owned();
        let transition = planted_transition(1.0);
        let closed = LinearStateQuotient::close(&[readout.view()], &[transition.view()])
            .expect("close");
        assert_eq!(closed.chart.nrows(), 2);
        let unclosed =
            LinearStateQuotient::measure(readout.clone(), &[readout.view()], &[transition.view()])
                .expect("measure");
        let leak = unclosed.quotient_bounds[0].lower;
        assert!(leak > 0.0);
        assert!(closed.quotient_bounds[0].upper < leak);
        assert!(closed.readout_bounds[0].upper < leak);
        assert!(closed.realization_bounds[0].lower > 0.0);

        let static_chart = LinearStateQuotient::close(&[readout.view()], &[]).expect("close");
        assert_eq!(static_chart.chart.nrows(), 1);
    }

    /// The linear counting shear `T(z, n) = (z, n + z)` observed through `z`: the
    /// code descends exactly, and the stationary realization `D = Qᵀ` is off by
    /// `[0; 1]`, norm 1. Control: observing `n` closes to the whole plane.
    #[test]
    fn counting_shear_descends_but_is_not_realized() {
        let shear = array![[1.0, 0.0], [1.0, 1.0]];
        let observe_first = array![[1.0, 0.0]];
        let quotient = LinearStateQuotient::measure(
            observe_first.clone(),
            &[observe_first.view()],
            &[shear.view()],
        )
        .expect("measure");
        assert_eq!(quotient.quotient_bounds[0].lower, 0.0);
        let realization = quotient.realization_bounds[0];
        assert!(
            realization.lower > 0.0 && realization.lower <= 1.0 && 1.0 <= realization.upper,
            "the realization defect 1 must lie in {realization:?}"
        );

        let observe_second = array![[0.0, 1.0]];
        let closed = LinearStateQuotient::close(&[observe_second.view()], &[shear.view()])
            .expect("close");
        assert_eq!(closed.chart.nrows(), 2);
    }

    /// Verdicts decide each evaluated item through the status supports.rs owns.
    /// Two items whose unrounded differences tie can differ in certification:
    /// with zero roundoff the difference is not rounded, otherwise it is rounded
    /// down. The owned lower bound tells them apart. The counterexample
    /// constructor reads the same derivation at the tie, and the record keeps the
    /// certified item.
    #[test]
    fn verdicts_decide_through_the_owned_status_the_counterexample_reads() {
        let tiny = f64::from_bits(1);
        let (uncertified_value, uncertified_roundoff) = (2.0 * tiny, tiny);
        let (certified_value, certified_roundoff) = (tiny, 0.0);
        assert_eq!(
            uncertified_value - uncertified_roundoff,
            certified_value - certified_roundoff,
            "the unrounded differences tie"
        );
        let uncertified =
            evaluated_defect(uncertified_value, uncertified_roundoff).expect("finite item");
        let certified = evaluated_defect(certified_value, certified_roundoff).expect("finite item");
        assert!(!uncertified.refutes_at_most(0.0));
        assert!(certified.refutes_at_most(0.0));
        assert!(certified_lower(&certified) > certified_lower(&uncertified));
        assert!(
            EvidenceStatus::<(), ()>::counterexample(
                uncertified_value,
                uncertified_roundoff,
                0.0,
                ()
            )
            .is_err()
        );
        assert!(
            EvidenceStatus::<(), ()>::counterexample(certified_value, certified_roundoff, 0.0, ())
                .is_ok()
        );

        let mut record = DefectRecord::new();
        record
            .observe(0, uncertified_value, uncertified_roundoff)
            .expect("finite item");
        record
            .observe(1, certified_value, certified_roundoff)
            .expect("finite item");
        assert!(matches!(record.violation, Some((1, _, _, _))));
    }

    /// The stacked-factor resolver refuses what it cannot resolve: a non-finite
    /// entry or formation, a negative formation, an empty factor. Control:
    /// `[[3, 4]]` resolves to rank 1, at its ceiling, with singular value 5 within
    /// the resolver's own band.
    #[test]
    fn stacked_factor_resolver_refuses_invalid_input() {
        let resolved = resolve_stacked_factor(&array![[3.0, 4.0]], 0.0).expect("resolve");
        assert_eq!((resolved.resolved_rank, resolved.rank_ceiling), (1, 1));
        assert!((resolved.singular_values[0] - 5.0).abs() <= resolved.band);
        assert!(matches!(
            resolve_stacked_factor(&array![[f64::NAN]], 0.0),
            Err(StateError::NonFinite { .. })
        ));
        assert!(matches!(
            resolve_stacked_factor(&array![[1.0]], f64::INFINITY),
            Err(StateError::NonFinite { .. })
        ));
        assert!(matches!(
            resolve_stacked_factor(&array![[1.0]], -1.0),
            Err(StateError::NegativeBound { value, .. }) if value == -1.0
        ));
        assert!(matches!(
            resolve_stacked_factor(&Array2::<f64>::zeros((0, 2)), 0.0),
            Err(StateError::EmptyFamily { .. })
        ));
    }

    /// Descent carries the mechanism (P13 into P3). A plane rotation by `0.9`,
    /// hidden in the ½-Hadamard frame, is observed through a readout inside its
    /// plane.
    /// * The closure recovers the plane.
    /// * The landed spectral owner reads the descended map `G = Q T Qᵀ` as exactly
    ///   one rotation plane.
    /// * Its certified cosine interval must overlap the one spectral certifies for
    ///   `T` itself. Both contain the true cosine, so no tolerance is chosen here.
    ///
    /// Control: a readout in the rotation's fixed space closes to one row, and
    /// spectral reads its descended map as the identity.
    #[test]
    fn descended_rotation_is_recovered_by_the_spectral_owner() {
        use crate::parameter_decomposition::spectral::{
            PlaneRotationRecovery, RotationAmbiguity, RotationClusterKind,
            recover_plane_rotations,
        };

        fn single_plane_cosines(recovery: &PlaneRotationRecovery) -> Option<(f64, f64)> {
            recovery
                .clusters
                .iter()
                .find_map(|cluster| match cluster.kind {
                    RotationClusterKind::Rotation { planes: 1, .. } => {
                        Some(cluster.cosine_interval)
                    }
                    _ => None,
                })
        }

        /// A derived bound on the 2-norm distance from a descended map `G` to the
        /// orthogonal group. It uses `measure`'s certified section bound `s ≥ ‖QQᵀ − I‖`
        /// and realization bound `r ≥ ‖R‖` with `R = TQᵀ − QᵀG`, and `t = 2ε + ε²`
        /// bounds `‖TᵀT − I‖` when `T` lies within `ε` of an orthogonal matrix.
        /// Expanding
        /// `GᵀG − I = Gᵀ(I − QQᵀ)G + (QQᵀ − I) + Q(TᵀT − I)Qᵀ − QTᵀR − RᵀTQᵀ + RᵀR`
        /// with `‖Q‖² ≤ 1 + s` and `‖G‖ ≤ ((1 + ε)√(1 + s) + r)/√(1 − s)` bounds `‖GᵀG − I‖`. That
        /// bounds every `|σᵢ − 1| ≤ |σᵢ² − 1|`.
        fn descended_orthogonality_error(
            quotient: &LinearStateQuotient,
            transition_error: f64,
        ) -> f64 {
            let section = quotient.section_bounds.upper;
            let realization = quotient.realization_bounds[0].upper;
            assert!(
                section < 1.0,
                "the chart's section defect {section} must leave QQᵀ invertible"
            );
            let transition_gram = 2.0 * transition_error + transition_error * transition_error;
            let chart_norm_squared = 1.0 + section;
            let transition_norm = 1.0 + transition_error;
            // ‖QᵀG‖ = ‖TQᵀ − R‖ ≤ (1 + ε)√(1 + s) + r, and ‖QᵀGx‖² ≥ (1 − s)‖Gx‖², so
            // ‖G‖ is bounded by certified quantities only. G is the stored fl(Q T Qᵀ), not
            // the exact product.
            let descended_norm = (transition_norm * chart_norm_squared.sqrt() + realization)
                / (1.0 - section).sqrt();
            descended_norm * descended_norm * section
                + section
                + chart_norm_squared * transition_gram
                + 2.0 * chart_norm_squared.sqrt() * transition_norm * realization
                + realization * realization
        }

        let (sine, cosine) = 0.9_f64.sin_cos();
        let frame = dyadic_frame();
        let block = array![
            [cosine, -sine, 0.0, 0.0],
            [sine, cosine, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0]
        ];
        let transition = frame.dot(&block).dot(&frame);
        // T's distance to the orthogonal group, derived. The float block's singular
        // values are √(c² + s²) and 1, so its distance is at most |c² + s² − 1|,
        // counted with the rounding of forming it. H is exactly orthogonal (dyadic).
        // The two 4-term products H·B·H round within 2γ₅·(|H||B||H|) entrywise, whose
        // Frobenius norm bounds the spectral norm of the formation error.
        let block_gram = cosine * cosine + sine * sine;
        let block_defect = (block_gram - 1.0).abs() + accumulation_growth(3) * (block_gram + 1.0);
        let magnitudes = frame
            .mapv(f64::abs)
            .dot(&block.mapv(f64::abs))
            .dot(&frame.mapv(f64::abs));
        let transition_error = block_defect
            + 2.0 * accumulation_growth(5) * magnitudes.iter().map(|m| m * m).sum::<f64>().sqrt();
        let whole = recover_plane_rotations(transition.view(), transition_error)
            .expect("recovery of T");
        let (whole_low, whole_high) =
            single_plane_cosines(&whole).expect("T rotates exactly one plane");

        let in_plane = frame.slice(s![..1, ..]).to_owned();
        let closed = LinearStateQuotient::close(&[in_plane.view()], &[transition.view()])
            .expect("close");
        assert_eq!(closed.chart.nrows(), 2);
        let descended_error = descended_orthogonality_error(&closed, transition_error);
        let descended = recover_plane_rotations(closed.descended[0].view(), descended_error)
            .expect("recovery of G");
        assert_eq!(descended.clusters.len(), 1);
        let (low, high) = single_plane_cosines(&descended).expect("G rotates one plane");
        assert!(
            low <= whole_high && whole_low <= high,
            "certified cosine intervals [{low}, {high}] for G and [{whole_low}, {whole_high}] \
             for T must overlap"
        );
        // Width floor: the overlap alone would pass for an interval widened toward [-1, 1].
        // Spectral reports [lowest - β, highest + β], with β the declared error plus the
        // formation band γ₁‖G‖_F plus the 2×2 spectrum rounding band (at most 2ε). One
        // two-point cluster spans at most 2β, so the width is at most 4β, budgeted here from
        // this test's own quantities.
        let descended_frobenius = closed.descended[0]
            .iter()
            .map(|value| value * value)
            .sum::<f64>()
            .sqrt();
        let width_budget = 4.0
            * (descended_error
                + accumulation_growth(1) * descended_frobenius
                + 2.0 * f64::EPSILON);
        assert!(
            high - low <= width_budget,
            "G's cosine interval width {} exceeds its derived budget {width_budget}",
            high - low
        );
        assert_eq!(descended.ambiguities(), vec![RotationAmbiguity::Winding]);

        let fixed_readout = frame.slice(s![2..3, ..]).to_owned();
        let fixed = LinearStateQuotient::close(&[fixed_readout.view()], &[transition.view()])
            .expect("close");
        assert_eq!(fixed.chart.nrows(), 1);
        let identity = recover_plane_rotations(
            fixed.descended[0].view(),
            descended_orthogonality_error(&fixed, transition_error),
        )
        .expect("recovery of the fixed descent");
        assert_eq!(identity.ambiguities(), vec![RotationAmbiguity::Identity]);
    }
}
