//! End-to-end OBJECTIVE quality: gam's **SAS (sinh-arcsinh) inverse link** under
//! the binomial family must RECOVER THE TRUE probability surface generated by an
//! *asymmetric* link, and do so better than a misspecified symmetric link (probit)
//! and at least as well as the mature, correctly-specified comparator
//! (`mgcv::gam(..., family = binomial(link = "cloglog"))`).
//!
//! Why this test earns its place. The SAS link is currently covered ONLY by a
//! jet-correctness test (`quality_vs_scipy_johnsonsu_sas_link_transform_math`)
//! that checks the closed-form inverse link and its derivatives against scipy —
//! it never *fits* anything. This test exercises the whole SAS-link FIT path:
//! gam jointly estimates the smooth `s(x)` AND the link's skew `epsilon` / tail
//! `delta` so that a single learnable link adapts to the unknown asymmetry of the
//! generating process. The SAS inverse link is
//!   `mu(eta) = Phi( sinh( B * tanh( (delta*asinh(eta) - epsilon) / B ) ) )`,
//! which at `epsilon=0, delta=1` reduces to probit; nonzero `epsilon` introduces
//! exactly the skew a fixed symmetric link cannot represent.
//!
//! Ground truth. The binary response is drawn from a KNOWN asymmetric latent
//! probability built through the **cloglog** inverse link
//!   `p_true(x) = 1 - exp(-exp(eta_true(x)))`,  `eta_true(x) = 1.1*sin(pi*x) - 0.4`,
//! which is strongly skewed (cloglog approaches 1 much faster than 0). A fixed
//! probit/logit GAM is therefore MISSPECIFIED: it cannot match both tails. gam's
//! SAS link should learn the asymmetry and recover `p_true`.
//!
//! Objective metrics asserted:
//!   1. PRIMARY (truth recovery): RMSE(gam_sas_prob, p_true) on the held-in
//!      covariate is a small fraction of the probability signal's range.
//!   2. SPECIFICATION GAIN (tool-free): the SAS fit recovers the truth at least
//!      as well as a fixed-probit GAM on the IDENTICAL data — the flexible link
//!      must not be worse than the rigid one it generalizes. We require
//!      `rmse_sas <= rmse_probit * 1.02`, a hard no-regression bound that lets a
//!      genuine tie through but forbids the flexible link degrading the fit.
//!   3. MATCH-OR-BEAT (mature comparator): RMSE(gam_sas, truth) is no worse than
//!      mgcv's correctly-specified `binomial(cloglog)` smooth by more than 15%.
//!      mgcv is handed the TRUE link, so it is a strong upper reference; gam's
//!      SAS link discovers the asymmetry rather than being told it.
//!
//! The same fixed-seed `{x, y}` data is handed to all three fits, scored against
//! the identical `p_true`.

use gam::estimate::FittedLinkState;
use gam::families::inverse_link::apply_inverse_link_spec_vec;
use gam::matrix::LinearOperator;
use gam::smooth::build_term_collection_design;
use gam::test_support::reference::{Column, pearson, r_package_available, relative_l2, rmse, run_r};
use gam::types::{InverseLink, StandardLink};
use gam::{
    FitConfig, FitResult, encode_recordswith_inferred_schema, fit_from_formula, init_parallelism,
};
use ndarray::Array2;
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand_distr::{Distribution, Uniform};
use std::f64::consts::PI;

const N: usize = 400;

/// True asymmetric latent linear predictor.
fn eta_true(x: f64) -> f64 {
    1.1 * (PI * x).sin() - 0.4
}

/// KNOWN generating probability via the **cloglog** inverse link (asymmetric):
/// `p = 1 - exp(-exp(eta))`.
fn p_true_cloglog(x: f64) -> f64 {
    let e = eta_true(x);
    1.0 - (-(e.exp())).exp()
}

#[test]
fn gam_sas_link_recovers_asymmetric_binary_probability() {
    init_parallelism();

    // ---- identical fixed-seed data for all fits --------------------------------
    let mut rng = StdRng::seed_from_u64(20260622);
    let ux = Uniform::new(0.0_f64, 1.0).expect("uniform [0,1]");
    let u01 = Uniform::new(0.0_f64, 1.0).expect("uniform [0,1]");

    let mut x = Vec::with_capacity(N);
    let mut y = Vec::with_capacity(N);
    let mut truth = Vec::with_capacity(N);
    for _ in 0..N {
        let xi = ux.sample(&mut rng);
        let p = p_true_cloglog(xi);
        let draw = if u01.sample(&mut rng) < p { 1.0 } else { 0.0 };
        x.push(xi);
        y.push(draw);
        truth.push(p);
    }

    // The response must be a genuine two-class signal.
    let n_pos: usize = y.iter().filter(|&&v| v > 0.5).count();
    assert!(
        n_pos > 40 && n_pos < N - 40,
        "synthetic binary response is degenerate: {n_pos}/{N} positive"
    );
    // The latent probability must carry real signal AND real asymmetry — the
    // whole point is that a symmetric link is misspecified. cloglog with this eta
    // spans a wide, skewed range.
    let p_min = truth.iter().cloned().fold(f64::INFINITY, f64::min);
    let p_max = truth.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let signal_range = p_max - p_min;
    assert!(
        signal_range > 0.4,
        "latent probability signal too flat to test recovery: range={signal_range:.3}"
    );

    // ---- encode the shared dataset --------------------------------------------
    let headers: Vec<String> = ["x", "y"].into_iter().map(String::from).collect();
    let mut rows = Vec::with_capacity(N);
    for i in 0..N {
        rows.push(csv::StringRecord::from(vec![
            x[i].to_string(),
            y[i].to_string(),
        ]));
    }
    let ds = encode_recordswith_inferred_schema(headers, rows).expect("encode binary dataset");
    let col = ds.column_map();
    let x_idx = col["x"];
    let p_cols = ds.headers.len();

    // Rebuild the frozen `s(x)` design at the training covariate and return the
    // linear predictor `X*beta` (= eta on the link scale).
    let eta_at_train = |resolvedspec: &gam::smooth::TermCollectionSpec, beta: &ndarray::Array1<f64>| -> Vec<f64> {
        let mut grid = Array2::<f64>::zeros((N, p_cols));
        for i in 0..N {
            grid[[i, x_idx]] = x[i];
        }
        let design = build_term_collection_design(grid.view(), resolvedspec)
            .expect("rebuild s(x) design at training points");
        design.design.apply(beta).to_vec()
    };

    // ---- fit gam with the SAS (sinh-arcsinh) inverse link ---------------------
    // family=binomial, link=sas: gam jointly estimates s(x) and the link's
    // skew/tail (epsilon, delta).
    let cfg_sas = FitConfig {
        family: Some("binomial".to_string()),
        link: Some("sas".to_string()),
        ..FitConfig::default()
    };
    let result_sas =
        fit_from_formula("y ~ s(x)", &ds, &cfg_sas).expect("gam binomial SAS-link smooth fit");
    let FitResult::Standard(fit_sas) = result_sas else {
        panic!("expected a standard GAM fit for binomial/sas s(x)");
    };
    let sas_edf = fit_sas.fit.edf_total().expect("gam reports total edf (sas)");

    // The SAS link state must have been fitted and stored.
    let (sas_link, sas_eps, sas_delta) = match &fit_sas.fit.fitted_link {
        FittedLinkState::Sas { state, .. } => (InverseLink::Sas(*state), state.epsilon, state.delta),
        other => panic!("expected a fitted SAS link state, got {other:?}"),
    };

    let gam_sas_eta = eta_at_train(&fit_sas.resolvedspec, &fit_sas.fit.beta);
    let gam_sas_prob = apply_inverse_link_spec_vec(&gam_sas_eta, &sas_link)
        .expect("evaluate fitted SAS inverse link on training etas");
    // Proper-mean range: every SAS-link probability must lie in (0,1).
    assert!(
        gam_sas_prob.iter().all(|&p| p > 0.0 && p < 1.0),
        "SAS inverse link must produce proper probabilities in (0,1)"
    );

    // ---- fit gam with a FIXED PROBIT link on the IDENTICAL data ---------------
    // This is the misspecified symmetric baseline the flexible link generalizes.
    let cfg_probit = FitConfig {
        family: Some("binomial".to_string()),
        link: Some("probit".to_string()),
        ..FitConfig::default()
    };
    let result_probit =
        fit_from_formula("y ~ s(x)", &ds, &cfg_probit).expect("gam binomial probit smooth fit");
    let FitResult::Standard(fit_probit) = result_probit else {
        panic!("expected a standard GAM fit for binomial/probit s(x)");
    };
    let probit_link = InverseLink::Standard(StandardLink::Probit);
    let gam_probit_eta = eta_at_train(&fit_probit.resolvedspec, &fit_probit.fit.beta);
    let gam_probit_prob = apply_inverse_link_spec_vec(&gam_probit_eta, &probit_link)
        .expect("evaluate probit inverse link on training etas");

    // ---- OBJECTIVE truth-recovery errors --------------------------------------
    let rmse_sas = rmse(&gam_sas_prob, &truth);
    let rmse_probit = rmse(&gam_probit_prob, &truth);

    // ---- mature comparator: mgcv binomial(cloglog) (TRUE link) ----------------
    let mgcv_rmse_truth = if r_package_available("mgcv") {
        let r = run_r(
            &[Column::new("x", &x), Column::new("y", &y)],
            r#"
            suppressPackageStartupMessages(library(mgcv))
            m <- gam(y ~ s(x), data = df, family = binomial(link = "cloglog"),
                     method = "REML")
            # fitted probabilities at the SAME training x (response scale).
            emit("prob", as.numeric(predict(m, type = "response")))
            emit("edf", sum(m$edf))
            "#,
        );
        let mgcv_prob = r.vector("prob");
        let mgcv_edf = r.scalar("edf");
        assert_eq!(mgcv_prob.len(), N, "mgcv probability length mismatch");
        let mgcv_rmse = rmse(mgcv_prob, &truth);
        let rel_sas_mgcv = relative_l2(&gam_sas_prob, mgcv_prob);
        let corr_sas_mgcv = pearson(&gam_sas_prob, mgcv_prob);
        eprintln!(
            "SAS-link asymmetric binary: n={N} signal_range={signal_range:.3} \
             eps={sas_eps:.4} delta={sas_delta:.4} sas_edf={sas_edf:.3} mgcv_edf={mgcv_edf:.3} \
             RMSE_to_truth[sas={rmse_sas:.4} probit={rmse_probit:.4} mgcv_cloglog={mgcv_rmse:.4}] \
             [context] rel_l2(sas,mgcv)={rel_sas_mgcv:.4} pearson(sas,mgcv)={corr_sas_mgcv:.5}"
        );
        Some(mgcv_rmse)
    } else {
        eprintln!(
            "mgcv unavailable — asserting gam-side truth recovery + specification gain only: \
             n={N} signal_range={signal_range:.3} eps={sas_eps:.4} delta={sas_delta:.4} \
             RMSE_to_truth[sas={rmse_sas:.4} probit={rmse_probit:.4}]"
        );
        None
    };

    // ---- PRIMARY: recover the true asymmetric probability surface -------------
    // Bar: a quarter of the probability signal's own range. With n=400 binary
    // draws a correct SAS-link fit reconstructs the generating curve rather than
    // the Bernoulli noise.
    let truth_bar = 0.25 * signal_range;
    assert!(
        rmse_sas < truth_bar,
        "gam SAS-link failed to recover the true asymmetric probability curve: \
         RMSE_to_truth={rmse_sas:.4} (bound {truth_bar:.4} = 0.25*signal_range)"
    );

    // ---- SPECIFICATION GAIN: the flexible link must not REGRESS vs fixed probit.
    // The SAS link strictly generalizes probit (epsilon=0, delta=1 IS probit), so
    // a correctly fitted SAS link can never be meaningfully worse than probit on
    // the same data; on the skewed cloglog truth it should be at least as good.
    // A 2% slack absorbs optimizer/round-off noise without letting a real
    // regression pass.
    assert!(
        rmse_sas <= rmse_probit * 1.02,
        "SAS link (a probit generalization) regressed vs fixed probit on skewed data: \
         rmse_sas={rmse_sas:.4} > rmse_probit*1.02={:.4}",
        rmse_probit * 1.02
    );

    // ---- MATCH-OR-BEAT mgcv's correctly-specified cloglog smooth --------------
    if let Some(mgcv_rmse) = mgcv_rmse_truth {
        assert!(
            rmse_sas <= mgcv_rmse * 1.15,
            "gam SAS-link truth recovery must match-or-beat mgcv's correctly-specified \
             binomial(cloglog): rmse_sas={rmse_sas:.4} vs mgcv*1.15={:.4}",
            mgcv_rmse * 1.15
        );
    }

    // EDF sanity: a real smooth was fitted, not a collapsed line or an overfit.
    assert!(
        sas_edf > 1.0 && sas_edf < 25.0,
        "gam SAS-link effective dof out of sane range: {sas_edf:.3}"
    );
}
