"""Sparse-autoencoder manifold fits, dictionary learning, and their audits.

This is the research surface of gamfit: :func:`sae_manifold_fit` and
:class:`ManifoldSAE`, sparse / linear dictionary fits, spectral and trust
diagnostics, shape censuses, structure discovery, layer transport,
crosscoder / behavior / checkpoint-dynamics fits, and parameter decomposition.
Importing :mod:`gamfit` does not load it; ``gamfit.sae`` is imported on first use.
"""

from __future__ import annotations

from ._api import (
    model_from_dict,
)
from ._rust import (
    adjudicate_atom_shape,
    shape_matched_control,
    shape_matched_control_f32,
)
from ._shape_census import (
    LabelShuffleMarginNull,
    ShapeControlledCensus,
    run_label_shuffle_margin_null,
    run_shape_controlled_census,
)
from ._linear_dictionary import (
    LinearDictionaryFit,
    linear_dictionary_fit,
)
from ._sparse_dictionary import (
    BlockSparseDictStream,
    BlockSparseDictionaryConvergence,
    BlockSparseDictionaryFit,
    BlockSparseStreamArtifact,
    BlockSparseStreamConvergence,
    SparseDictStream,
    SparseDictStreamArtifact,
    SparseDictionaryConvergence,
    SparseDictionaryFit,
    block_sparse_dictionary_fit,
    block_sparse_dictionary_fit_begin,
    fixed_budget_block_sparse_dictionary_fit,
    sparse_dictionary_fit,
    sparse_dictionary_fit_begin,
)
from ._sae_spectral import (
    AtlasNerveDiagram,
    AtomRetentionEvidence,
    BlockCoordinateReport,
    ChartInterpNullCalibration,
    ChartInterpNullCalibrationReport,
    ChartInterpNullProtocol,
    ChartInterpReadout,
    ChartInterpReport,
    ChartInterpStatisticValue,
    ComposedContract,
    ConditionalCoactivationInfluence,
    CoordinatePosterior,
    CouplingRobustnessCertificate,
    DoseResponseCalibrationReport,
    DualCertificateReport,
    FisherEffectEvidence,
    HolonomyReport,
    RoutabilityAudit,
    RoutabilityFloor,
    SpectrometerReport,
    SpikeRecovery,
    StageContainment,
    VarianceChargeEvidence,
    WholeSetContainment,
    atlas_nerve_diagram,
    audit_sae,
    block_firing_coordinates,
    chart_interp_score,
    compose_contracts,
    conditional_coactivation_influence,
    coordinate_posterior_from_precision,
    coupling_robustness_certificate,
    dimension_spectrometer,
    dose_response_calibration,
    effect_weighted_retention,
    loop_holonomy,
    recover_spikes,
    routability_audit,
    routability_floor,
    separation_limit,
    sparse_dict_dual_certificate,
    whole_set_containment,
)
from ._equivariant import (
    GaugeCompanion,
    gauge_companion,
    rho_so2,
    rho_so2_jvp,
    rho_so3,
    rho_so3_jvp,
)
from ._sae_manifold import (
    GumbelTemperatureSchedule,
    ManifoldSAE,
    flat_block_assignment,
    gumbel_geometric_schedule,
    gumbel_linear_schedule,
    gumbel_reciprocal_iter_schedule,
    sae_manifold_certify_external,
    sae_manifold_fit,
)
from ._sae_trust import (
    atom_trust_scores,
    sae_trust_diagnostics,
)
from ._structure_discovery import (
    atom_birth_gate,
    e_bh_dictionary_certificate,
    expected_resolution_budget,
    log_e_from_p_value,
    plan_probe_for_contested_claim,
    select_probe_by_expected_evidence,
    split_likelihood_log_e,
)
from ._layer_transport import (
    certify_chart_transfer,
    chart_transfer_operator,
    fit_transport,
    layer_transport_fit,
    layer_transport_ladder,
)
from ._manifold_crosscoder import (
    sae_crosscoder_fit,
)
from ._manifold_behavior import (
    sae_behavior_fit,
)
from ._checkpoint_dynamics import (
    sae_checkpoint_dynamics,
)
from ._intervention_calibration import (
    ChartCalibration,
    fit_chart_calibration,
)
from ._parameter_decomposition import (
    ParameterDecompositionReport,
    robust_support,
    run_parameter_decomposition,
)

__all__ = [
    "adjudicate_atom_shape",
    "atlas_nerve_diagram",
    "AtlasNerveDiagram",
    "atom_birth_gate",
    "atom_trust_scores",
    "AtomRetentionEvidence",
    "audit_sae",
    "block_firing_coordinates",
    "block_sparse_dictionary_fit",
    "block_sparse_dictionary_fit_begin",
    "BlockCoordinateReport",
    "BlockSparseDictionaryConvergence",
    "BlockSparseDictionaryFit",
    "BlockSparseDictStream",
    "BlockSparseStreamArtifact",
    "BlockSparseStreamConvergence",
    "certify_chart_transfer",
    "chart_interp_score",
    "chart_transfer_operator",
    "ChartCalibration",
    "ChartInterpNullCalibration",
    "ChartInterpNullCalibrationReport",
    "ChartInterpNullProtocol",
    "ChartInterpReadout",
    "ChartInterpReport",
    "ChartInterpStatisticValue",
    "compose_contracts",
    "ComposedContract",
    "conditional_coactivation_influence",
    "ConditionalCoactivationInfluence",
    "coordinate_posterior_from_precision",
    "CoordinatePosterior",
    "coupling_robustness_certificate",
    "CouplingRobustnessCertificate",
    "dimension_spectrometer",
    "dose_response_calibration",
    "DoseResponseCalibrationReport",
    "DualCertificateReport",
    "e_bh_dictionary_certificate",
    "effect_weighted_retention",
    "expected_resolution_budget",
    "FisherEffectEvidence",
    "fit_chart_calibration",
    "fit_transport",
    "fixed_budget_block_sparse_dictionary_fit",
    "flat_block_assignment",
    "gauge_companion",
    "GaugeCompanion",
    "gumbel_geometric_schedule",
    "gumbel_linear_schedule",
    "gumbel_reciprocal_iter_schedule",
    "GumbelTemperatureSchedule",
    "HolonomyReport",
    "LabelShuffleMarginNull",
    "layer_transport_fit",
    "layer_transport_ladder",
    "linear_dictionary_fit",
    "LinearDictionaryFit",
    "log_e_from_p_value",
    "loop_holonomy",
    "ManifoldSAE",
    "model_from_dict",
    "ParameterDecompositionReport",
    "plan_probe_for_contested_claim",
    "recover_spikes",
    "rho_so2",
    "rho_so2_jvp",
    "rho_so3",
    "rho_so3_jvp",
    "routability_audit",
    "routability_floor",
    "RoutabilityAudit",
    "RoutabilityFloor",
    "run_label_shuffle_margin_null",
    "robust_support",
    "run_parameter_decomposition",
    "run_shape_controlled_census",
    "sae_behavior_fit",
    "sae_checkpoint_dynamics",
    "sae_crosscoder_fit",
    "sae_manifold_certify_external",
    "sae_manifold_fit",
    "sae_trust_diagnostics",
    "select_probe_by_expected_evidence",
    "separation_limit",
    "shape_matched_control",
    "shape_matched_control_f32",
    "ShapeControlledCensus",
    "sparse_dict_dual_certificate",
    "sparse_dictionary_fit",
    "sparse_dictionary_fit_begin",
    "SparseDictionaryConvergence",
    "SparseDictionaryFit",
    "SparseDictStream",
    "SparseDictStreamArtifact",
    "SpectrometerReport",
    "SpikeRecovery",
    "split_likelihood_log_e",
    "StageContainment",
    "VarianceChargeEvidence",
    "whole_set_containment",
    "WholeSetContainment",
]
